USE ZEUSS

DECLARE @FECHA AS DATE
DECLARE @SABADO AS BIT
DECLARE @DOMINGO AS BIT
DECLARE @FESTIVO AS BIT
DECLARE @DIA_HABIL AS INTEGER
DECLARE @DIA_HABIL2 AS INTEGER
DECLARE @DOMINGO2 AS BIT
DECLARE @FESTIVO2 AS BIT
DECLARE @FECHA_INI AS DATE='01/01/2018'
DECLARE @FECHA_FIN AS DATE=DATEADD(DAY,-1,@FECHA_INI)

UPDATE y_calendario
SET dia_habil=0
WHERE fecha>=@FECHA_INI

DECLARE YCAL CURSOR    
   
FOR 

SELECT FECHA,SABADO,DOMINGO,FESTIVO,DIA_HABIL
FROM Y_CALENDARIO
WHERE FECHA>=@FECHA_INI
ORDER BY FECHA ASC

OPEN YCAL


 FETCH NEXT FROM YCAL INTO @FECHA,@SABADO,@DOMINGO,@FESTIVO,@DIA_HABIL
 
 WHILE @@FETCH_STATUS = 0  
    BEGIN 
			SELECT 	@DIA_HABIL2=
			CASE WHEN FECHA=@FECHA_FIN THEN 0 ELSE DIA_HABIL END ,
			@DOMINGO2=domingo,@FESTIVO2=festivo
			FROM y_calendario
			WHERE fecha=DATEADD(DAY,-1,@FECHA)
    
    
				IF (@DOMINGO=1 OR @FESTIVO=1) AND @DIA_HABIL2<>0
			BEGIN			
				
				UPDATE y_calendario
				SET dia_habil=@DIA_HABIL2
				WHERE fecha=@FECHA	
			END
			IF NOT (@DOMINGO=1 OR @FESTIVO=1) AND @DIA_HABIL2<>0
			BEGIN
				IF DAY(@FECHA)=1 
				BEGIN
					SET @DIA_HABIL2=0
				END
				
				
				UPDATE y_calendario
				SET dia_habil=@DIA_HABIL2+1
				WHERE fecha=@FECHA	
				
			END
		
    
			IF DAY(@FECHA)=1 AND (@DOMINGO=1 OR @FESTIVO=1 )
			BEGIN
				UPDATE y_calendario
				SET dia_habil=1
				WHERE fecha=@FECHA			
			END
			
			IF DAY(@FECHA)=2 
			BEGIN
								
				IF @DIA_HABIL2=1  AND (@DOMINGO2=1 OR @FESTIVO2=1 )
				BEGIN
					UPDATE y_calendario
					SET dia_habil=1
					WHERE fecha=@FECHA	
				END
			END
			IF DAY(@FECHA)=3  
			BEGIN			
				
				IF @DIA_HABIL2=1 AND (@DOMINGO2=1 OR @FESTIVO2=1 )
				BEGIN
					UPDATE y_calendario
					SET dia_habil=1
					WHERE fecha=@FECHA	
				END
			END
		
			
			
 
 
		
	
 
		  FETCH NEXT FROM YCAL INTO @FECHA,@SABADO,@DOMINGO,@FESTIVO,@DIA_HABIL
	END
 

 
 CLOSE YCAL
 
 DEALLOCATE YCAL
 
 