DECLARE @CONT AS INTEGER=1
DECLARE @FECHA AS DATE='31/12/2018'
WHILE @CONT<366
BEGIN
	INSERT INTO bon_calendario_tbl
	SELECT DATEADD(DAY,@CONT,@FECHA),0,0,0,NULL,0,0	
	SET @CONT=@CONT+1
END

UPDATE bon_calendario_tbl
SET domingo=(CASE WHEN DATEPART(DW,fecha)=7 THEN 1 ELSE 0 END),
 sabado=(CASE WHEN DATEPART(DW,fecha)=6 THEN 1 ELSE 0 END)
 WHERE fecha>@FECHA
 
 