SELECT P.CONCEPTO,TM.TIPO ,TM.NIT,TM.DIGITO,TM.PAPELLIDO,TM.SAPELLIDO,TM.PNOMBRE,TM.SNOMBRE,TM.RAZON_SOCIAL,TM.DIRECCION,TM.DEPARTAMENTO,TM.CIUDAD,TM.PAIS,SUM(P.VALOR) VALOR
FROM (

SELECT CASE WHEN M.cuenta IN ('130505') THEN 1315 
WHEN M.cuenta BETWEEN '1365' AND '138096zzzz' THEN 1317 ELSE 0 END CONCEPTO,T.nit_real NIT,
ROUND(SUM(M.saldo_inicial+M.debito-M.credito),0) VALOR
FROM cuentas_val M 
INNER JOIN terceros T ON (M.nit=T.nit)
WHERE M.ano=2016 AND M.MES=12 AND (M.cuenta IN ('130505') or M.cuenta BETWEEN '1365' AND '138096zzzz')
GROUP BY T.nit_real,M.cuenta
HAVING SUM(M.saldo_inicial+M.debito-M.credito) <>0 ) AS P LEFT JOIN terceros_medios TM ON (P.NIT=TM.NIT)
GROUP BY  P.CONCEPTO,TM.TIPO ,TM.NIT,TM.DIGITO,TM.PAPELLIDO,TM.SAPELLIDO,TM.PNOMBRE,TM.SNOMBRE,TM.RAZON_SOCIAL,TM.DIRECCION,TM.DEPARTAMENTO,TM.CIUDAD,TM.PAIS
HAVING SUM(P.VALOR)>100
ORDER BY P.CONCEPTO,TM.NIT	