SELECT Q.CONCEPTO,TM.TIPO,ISNULL(TM.NIT,Q.NIT) NIT,TM.DIGITO,TM.PAPELLIDO,TM.SAPELLIDO,TM.PNOMBRE,TM.SNOMBRE,TM.RAZON_SOCIAL,TM.PAIS,SUM(Q.K) K,0 L,0 M,0 N,0 O ,0 P,SUM(Q.Q) Q
FROM (


SELECT C.CONCEPTO,CASE WHEN C.K+C.Q <500000 THEN 222222222 ELSE NIT END NIT,C.K,C.Q
FROM (

SELECT T.CONCEPTO,T.NIT,SUM(K) K, SUM (Q) Q
FROM (


SELECT *
FROM (


SELECT CONCEPTO,NIT,SUM(K) K,0 Q
FROM (



)

AS P

GROUP BY CONCEPTO,NIT
HAVING SUM( K)<>0



) AS S 

UNION


SELECT 4001 CONCEPTO,T.nit_real NIT,0 K,SUM(valor) Q
FROM movimiento M 
INNER JOIN documentos D ON (M.tipo=D.tipo AND M.numero=D.numero)
INNER JOIN terceros T ON (D.nit=T.nit)
WHERE M.cuenta BETWEEN '4175' AND '4175zzzz' AND YEAR(M.fec)=2016 AND M.tipo<>'Z1'
GROUP BY T.nit_real


) AS T

GROUP BY T.CONCEPTO,T.NIT


) C ) AS Q left JOIN terceros_medios TM ON (Q.NIT=TM.NIT)

GROUP BY Q.CONCEPTO,Q.NIT,TM.TIPO,TM.NIT,TM.DIGITO,TM.PAPELLIDO,TM.SAPELLIDO,TM.PNOMBRE,TM.SNOMBRE,TM.RAZON_SOCIAL,TM.PAIS