DECLARE @TSQL AS VARCHAR(100)
DECLARE @RST AS INTEGER
DECLARE @TIPO AS VARCHAR(4)
DECLARE @NUMERO AS INTEGER
DECLARE @FECHA AS DATE
DECLARE @VALOR AS MONEY
DECLARE @SEQ AS INTEGER
DECLARE @NIT AS DECIMAL(18,0)
DECLARE @NOMBRE AS VARCHAR(60)
DECLARE @CELULAR AS VARCHAR(20)
DECLARE @MAIL AS VARCHAR(80)
DECLARE @CARGO AS VARCHAR(80)
DECLARE @COMENTARIOS AS VARCHAR(250)
DECLARE @CONTACTO AS INTEGER

SET @TSQL='CT_CONTACTO_COMPRAS'
SET @RST =0	


DECLARE CT_CONTACTO_COMPRAS CURSOR  
		
FOR			
	SELECT  T.nit,UPPER(ISNULL(FE.nombres,'') + ' ' + ISNULL(FE.Apellidos,'')) nombre,FE.celular,FE.email_710,'COMPRAS' cargo,'FE: ACTUALIZADO DESDE PLATAFORMA DE MERCADEO' comentarios
	FROM fe_correos_10092018 FE 
	LEFT JOIN terceros TR ON (FE.NIT=TR.nit) 
	LEFT JOIN terceros T ON (TR.nit=T.nit_real)
	WHERE ISNUMERIC(FE.NIT)=1 and T.nit IS NOT  NULL AND FE.NIT<>'0'

OPEN CT_CONTACTO_COMPRAS

FETCH NEXT FROM CT_CONTACTO_COMPRAS INTO @NIT,@NOMBRE,@CELULAR,@MAIL,@CARGO,@COMENTARIOS

WHILE @@FETCH_STATUS = 0  
BEGIN 	 
	SELECT @CONTACTO=ISNULL(MAX(contacto),0)+1
	FROM CRM_contactos
	WHERE nit=@NIT	
	
	INSERT INTO CRM_contactos (nit,contacto,nombre,tel_celular,e_mail,cargo,comentarios,LastUpdate)
	VALUES (@NIT,@CONTACTO,@NOMBRE,@CELULAR,@MAIL,@CARGO,@COMENTARIOS,GETDATE())		
			
				 
	FETCH NEXT FROM CT_CONTACTO_COMPRAS INTO  @NIT,@NOMBRE,@CELULAR,@MAIL,@CARGO,@COMENTARIOS
END
		
CLOSE CT_CONTACTO_COMPRAS
DEALLOCATE CT_CONTACTO_COMPRAS
		
		
