DECLARE @AÑO AS INTEGER=2018
DECLARE @MES AS INTEGER=8
DECLARE @DIA AS INTEGER=23
DECLARE @BODEGA AS INTEGER=1
DECLARE @DIA_HABIL AS INTEGER=0
DECLARE @DIA_MES AS INTEGER=0
DECLARE @FECHA AS DATE=NULL


SELECT @FECHA=CAST(CAST(@DIA AS VARCHAR)+'/'+CAST(@MES AS VARCHAR)+'/'+CAST(@AÑO AS VARCHAR) AS DATE)

SELECT @DIA_HABIL=dia_habil,@DIA_MES=ISNULL(dia_mes,27)
FROM bon_calendario_tbl
WHERE fecha=@FECHA



SELECT ETIQUETA,
SUBSTRING(CONVERT(VARCHAR(50),CAST(DIESEL AS MONEY),1),1,CHARINDEX('.',CONVERT(VARCHAR(50),CAST(DIESEL AS MONEY),1))-1) DIESEL,
SUBSTRING(CONVERT(VARCHAR(50),CAST(CORRIENTE AS MONEY),1),1,CHARINDEX('.',CONVERT(VARCHAR(50),CAST(CORRIENTE AS MONEY),1))-1) CORRIENTE,
SUBSTRING(CONVERT(VARCHAR(50),CAST(EXTRA AS MONEY),1),1,CHARINDEX('.',CONVERT(VARCHAR(50),CAST(EXTRA AS MONEY),1))-1) EXTRA,
SUBSTRING(CONVERT(VARCHAR(50),CAST(DIESEL_ECOEXTREME AS MONEY),1),1,CHARINDEX('.',CONVERT(VARCHAR(50),CAST(DIESEL_ECOEXTREME AS MONEY),1))-1) DIESEL_ECOEXTREME,
SUBSTRING(CONVERT(VARCHAR(50),CAST(TOTAL AS MONEY),1),1,CHARINDEX('.',CONVERT(VARCHAR(50),CAST(TOTAL AS MONEY),1))-1) TOTAL
FROM (

SELECT CASE 
WHEN DIA=90 THEN 'TOTAL'
WHEN DIA=91 THEN 'PROMEDIO'
WHEN DIA=92 THEN 'PROYECCION'
ELSE DATENAME(DW,FECHA) + ' ' + CAST(DIA AS varchar) END ETIQUETA,
CASE 
WHEN DIA=91 THEN ROUND(DIESEL/DIA_HABIL,0) 
WHEN DIA=92 THEN ROUND(DIESEL/DIA_HABIL,0)* DIA_MES
ELSE DIESEL END DIESEL,
CASE
WHEN DIA=91 THEN ROUND(CORRIENTE/DIA_HABIL,0) 
WHEN DIA=92 THEN ROUND(CORRIENTE/DIA_HABIL,0)* DIA_MES
ELSE CORRIENTE END CORRIENTE,
CASE
WHEN DIA=91 THEN ROUND(EXTRA/DIA_HABIL,0) 
WHEN DIA=92 THEN ROUND(EXTRA/DIA_HABIL,0)* DIA_MES
ELSE EXTRA END EXTRA,
CASE
WHEN DIA=91 THEN ROUND(DIESEL_ECOEXTREME/DIA_HABIL,0) 
WHEN DIA=92 THEN ROUND(DIESEL_ECOEXTREME/DIA_HABIL,0)* DIA_MES
ELSE DIESEL_ECOEXTREME END DIESEL_ECOEXTREME,
CASE
WHEN DIA=91 THEN ROUND(TOTAL/DIA_HABIL,0) 
WHEN DIA=92 THEN ROUND(TOTAL/DIA_HABIL,0)* DIA_MES
ELSE TOTAL END TOTAL,DIA
FROM (

SELECT 
CASE 
WHEN ANO IS NULL THEN 90
WHEN ANO IS NOT NULL AND MES IS NULL THEN 92
WHEN ANO IS NOT NULL AND MES IS NOT NULL AND DIA IS NULL THEN 91
ELSE DIA END DIA,
DIESEL ,CORRIENTE,EXTRA,DIESEL_ECOEXTREME,TOTAL,@DIA_HABIL DIA_HABIL,@DIA_MES DIA_MES,
CAST(CAST(DIA AS VARCHAR)+'/'+CAST(MES AS VARCHAR)+'/'+CAST(ANO AS VARCHAR) AS DATE) FECHA
FROM Zeuss_Lin_Ventas_tbl
WHERE BODEGA=@BODEGA AND (ANO=@AÑO OR (ANO IS NULL AND DIA IS NULL)) AND (MES=@MES OR (MES IS NULL AND DIA IS NULL AND ANO IS NOT NULL))
) AS P
) AS S
ORDER BY DIA
