DECLARE @HTML AS NVARCHAR(MAX)
DECLARE @PTOGENERAL AS NVARCHAR(MAX)
DECLARE @GENERAL AS NVARCHAR(MAX)
DECLARE @GIRARDOTA AS NVARCHAR(MAX)
DECLARE @TOCANCIPA AS NVARCHAR(MAX)
DECLARE @CANDELARIA AS NVARCHAR(MAX)
DECLARE @GALAPA AS NVARCHAR(MAX)
DECLARE @CARTAGO AS NVARCHAR(MAX)
DECLARE @PANO AS INTEGER=2018
DECLARE @PMES AS INTEGER=8
DECLARE @PDIA AS INTEGER=24

EXEC spInformeVentasDiarias_ContruccionTBL @ANO=@PANO,@MES=@PMES,@DIA=@PDIA

EXEC spInformeVentasDiarias_ContruccionDTLPTO @ANO=@PANO,@MES=@PMES,@DIA=@PDIA,@BODEGA=99,@HTML_SALIDA=@PTOGENERAL OUTPUT

EXEC spInformeVentasDiarias_ContruccionDTL @ANO=@PANO,@MES=@PMES,@DIA=@PDIA,@BODEGA=99,@HTML_SALIDA=@GENERAL OUTPUT
EXEC spInformeVentasDiarias_ContruccionDTL @ANO=@PANO,@MES=@PMES,@DIA=@PDIA,@BODEGA=1,@HTML_SALIDA=@GIRARDOTA OUTPUT
EXEC spInformeVentasDiarias_ContruccionDTL @ANO=@PANO,@MES=@PMES,@DIA=@PDIA,@BODEGA=2,@HTML_SALIDA=@TOCANCIPA OUTPUT
EXEC spInformeVentasDiarias_ContruccionDTL @ANO=@PANO,@MES=@PMES,@DIA=@PDIA,@BODEGA=3,@HTML_SALIDA=@CANDELARIA OUTPUT
EXEC spInformeVentasDiarias_ContruccionDTL @ANO=@PANO,@MES=@PMES,@DIA=@PDIA,@BODEGA=5,@HTML_SALIDA=@GALAPA OUTPUT
EXEC spInformeVentasDiarias_ContruccionDTL @ANO=@PANO,@MES=@PMES,@DIA=@PDIA,@BODEGA=6,@HTML_SALIDA=@CARTAGO OUTPUT


SET @HTML=ISNULL(@PTOGENERAL,'')+ISNULL(@GENERAL,'') + ISNULL(@GIRARDOTA,'') + ISNULL(@TOCANCIPA,'') + ISNULL(@CANDELARIA,'')+ ISNULL(@GALAPA,'')+ ISNULL(@CARTAGO,'')
  
IF LEN(@HTML)>0
BEGIN   
 EXEC msdb.dbo.sp_send_dbmail   
 @profile_name='AutoEnvio de Correos',  
 @blind_copy_recipients='jballesteros@zeuss.com.co' ,  
 @subject='Prueba de Ventas',  
 @body = @HTML,  
 @body_format = 'HTML'  
END  

