SELECT T.nit,T.nombres,ZT.CANTIDAD,
ROUND(CASE WHEN ZT.DIA_MES=0 THEN 0 ELSE (ZT.PRESUPUESTO/ZT.DIA_MES)*DIA_HABIL END,0) PRESUPUESTO,      
ZT.PRESUPUESTO PRESUPUESTO_MES,
ROUND(CASE WHEN ZT.DIA_MES=0 OR ZT.PRESUPUESTO=0 THEN 0 ELSE  (ZT.CANTIDAD/((ZT.PRESUPUESTO/ZT.DIA_MES)*DIA_HABIL))  END,2) CUMPLIMIENTO      
FROM Zeuss_Lin_Ventas_tbl_presupuesto_asesor ZT 
INNER JOIN terceros TV ON (ZT.COD_VEN=TV.nit)
LEFT JOIN terceros T ON (ZT.NIT=T.nit)
WHERE COD_VEN=122 AND ANO IS NOT NULL AND MES	IS NOT NULL AND BODEGA IS NOT NULL