SELECT P.AÑO,P.COD_VEN,P.VENDEDOR,P.ENERO,S.ENERO,
P.FEBRERO,S.FEBRERO,P.MARZO,S.MARZO,P.ABRIL,S.ABRIL,P.MAYO,S.MAYO,P.JUNIO,S.JUNIO,P.JULIO,S.JULIO,P.AGOSTO,S.AGOSTO,P.SEPTIEMBRE,S.SEPTIEMBRE,P.OCTUBRE,S.OCTUBRE,P.NOVIEMBRE,S.NOVIEMBRE,P.DICIEMBRE,S.DICIEMBRE
FROM (

SELECT ZL.ano AÑO,TV.nit COD_VEN,TV.nombres VENDEDOR,
SUM(CASE WHEN ZL.mes=1 THEN ZL.can_ventas-ZL.can_devolu ELSE 0 END) ENERO,
SUM(CASE WHEN ZL.mes=2 THEN ZL.can_ventas-ZL.can_devolu ELSE 0 END) FEBRERO,
SUM(CASE WHEN ZL.mes=3 THEN ZL.can_ventas-ZL.can_devolu ELSE 0 END) MARZO,
SUM(CASE WHEN ZL.mes=4 THEN ZL.can_ventas-ZL.can_devolu ELSE 0 END) ABRIL,
SUM(CASE WHEN ZL.mes=5 THEN ZL.can_ventas-ZL.can_devolu ELSE 0 END) MAYO,
SUM(CASE WHEN ZL.mes=6 THEN ZL.can_ventas-ZL.can_devolu ELSE 0 END) JUNIO,
SUM(CASE WHEN ZL.mes=7 THEN ZL.can_ventas-ZL.can_devolu ELSE 0 END) JULIO,
SUM(CASE WHEN ZL.mes=8 THEN ZL.can_ventas-ZL.can_devolu ELSE 0 END) AGOSTO,
SUM(CASE WHEN ZL.mes=9 THEN ZL.can_ventas-ZL.can_devolu ELSE 0 END) SEPTIEMBRE,
SUM(CASE WHEN ZL.mes=10 THEN ZL.can_ventas-ZL.can_devolu ELSE 0 END) OCTUBRE,
SUM(CASE WHEN ZL.mes=11 THEN ZL.can_ventas-ZL.can_devolu ELSE 0 END) NOVIEMBRE,
SUM(CASE WHEN ZL.mes=12 THEN ZL.can_ventas-ZL.can_devolu ELSE 0 END) DICIEMBRE

FROM Zeuss_Lin_Ventas ZL 
INNER JOIN terceros T ON (ZL.nit=T.nit)
INNER JOIN terceros TV ON (T.vendedor=TV.nit)
WHERE ZL.ano IN (2015,2016) AND ZL.subgrupo2 IN (2,3,4) AND NOT (ZL.nit IN (909871,909845)) AND NOT (ZL.nit IN (900467,900474) AND ZL.ano=2016)
GROUP BY TV.nit,TV.nombres,ZL.ano) AS P

FULL JOIN (

SELECT ZL.ano AÑO,TV.nit COD_VEN,TV.nombres VENDEDOR,

SUM(CASE WHEN ZL.mes=1 THEN ZL.galones ELSE 0 END) ENERO,
SUM(CASE WHEN ZL.mes=2 THEN ZL.galones ELSE 0 END) FEBRERO,
SUM(CASE WHEN ZL.mes=3 THEN ZL.galones ELSE 0 END) MARZO,
SUM(CASE WHEN ZL.mes=4 THEN ZL.galones ELSE 0 END) ABRIL,
SUM(CASE WHEN ZL.mes=5 THEN ZL.galones ELSE 0 END) MAYO,
SUM(CASE WHEN ZL.mes=6 THEN ZL.galones ELSE 0 END) JUNIO,
SUM(CASE WHEN ZL.mes=7 THEN ZL.galones ELSE 0 END) JULIO,
SUM(CASE WHEN ZL.mes=8 THEN ZL.galones ELSE 0 END) AGOSTO,
SUM(CASE WHEN ZL.mes=9 THEN ZL.galones ELSE 0 END) SEPTIEMBRE,
SUM(CASE WHEN ZL.mes=10 THEN ZL.galones ELSE 0 END) OCTUBRE,
SUM(CASE WHEN ZL.mes=11 THEN ZL.galones ELSE 0 END) NOVIEMBRE,
SUM(CASE WHEN ZL.mes=12 THEN ZL.galones ELSE 0 END) DICIEMBRE

FROM presupuesto ZL 
INNER JOIN terceros T ON (ZL.nit=T.nit)
INNER JOIN terceros TV ON (T.vendedor=TV.nit)
WHERE ZL.ano IN (2015,2016) 
GROUP BY TV.nit,TV.nombres,ZL.ano) AS S ON (P.AÑO=S.AÑO AND P.VENDEDOR=S.VENDEDOR)