DECLARE @INDEXNAME AS VARCHAR(500)
DECLARE @TABLENAME AS VARCHAR(500)
DECLARE @PORCENTAJE AS FLOAT


DECLARE MAN_IND CURSOR
FOR

SELECT IndexName,TableName,avg_fragmentation_in_percent
FROM indices_mantenimiento
WHERE IndexName IS NOT NULL AND avg_fragmentation_in_percent>60 

OPEN MAN_IND

FETCH NEXT FROM MAN_IND INTO @INDEXNAME,@TABLENAME,@PORCENTAJE


WHILE @@FETCH_STATUS = 0  
		BEGIN 			
			EXEC ('ALTER INDEX ' + @INDEXNAME + ' ON ' +  @TABLENAME + ' REBUILD' )			
			
			PRINT @INDEXNAME + ' - ' + @TABLENAME

			FETCH NEXT FROM MAN_IND INTO @INDEXNAME,@TABLENAME,@PORCENTAJE
		END


		CLOSE MAN_IND
		DEALLOCATE MAN_IND