SELECT *
FROM (

SELECT *,CASE WHEN APAR=1 THEN ISNULL(RETENCION,0) ELSE 0 END RETENCION_F,
CASE WHEN APAR=1 THEN ISNULL(RETE_INVA,0) ELSE 0 END RETE_IVA_F,
CASE WHEN APAR=1 THEN ISNULL(NO_DEDUC,0) ELSE 0 END NO_DEDUC_F,
CASE WHEN APAR=1 THEN ISNULL(IVA_MAY,0) ELSE 0 END IVA_MAY_F
FROM (

SELECT S.CONCEPTO,TM.TIPO,ISNULL(TM.NIT,S.NIT) NIT,TM.DIGITO,TM.PAPELLIDO,TM.SAPELLIDO,TM.PNOMBRE,TM.SNOMBRE,TM.RAZON_SOCIAL,PAIS,SUM(S.VALOR) VALOR, RM.CREDITO RETENCION,RM.RETE_INVA,RM.NO_DEDUC ,RM.IVA_MAY,
ROW_NUMBER () OVER  (PARTITION BY TM.NIT ORDER BY TM.NIT) APAR
FROM (
SELECT *



FROM (

SELECT CF.CONCEPTO CONCEPTO,CV.cuenta,
 TR.NIT  NIT,
ROUND(SUM(CASE WHEN CF.concepto IN (5008,5035,5032,5007) THEN  CV.debito 
			WHEN CF.concepto IN (5049,5050,5051,5052,5062)	 THEN CV.credito
			ELSE (CASE WHEN CV.MES=12 THEN CV.SALDO_INICIAL+ CV.debito- CV.credito ELSE 0 END) END ),0) VALOR
FROM cuentas_val CV 
INNER JOIN cuentas_formatos CF ON (CV.cuenta=CF.cuenta)

LEFT JOIN terceros T ON (CV.NIT=T.nit)
LEFT JOIN terceros TR ON (T.nit_real=TR.nit)
WHERE CF.formato=1001 AND CV.ano=2015 AND CV.mes<>13   
GROUP BY  CF.formato ,CF.concepto ,TR.NIT,CV.cuenta
) AS P


) AS S

LEFT JOIN terceros_medios TM ON (S.NIT=TM.NIT)
LEFT JOIN retencion_medios RM ON (S.NIT=RM.NIT)
GROUP BY S.CONCEPTO,S.NIT,TM.TIPO,TM.NIT,TM.DIGITO,TM.PAPELLIDO,TM.SAPELLIDO,TM.PNOMBRE,TM.SNOMBRE,TM.RAZON_SOCIAL,TM.PAIS,TM.DIRECCION,TM.CIUDAD,TM.DEPARTAMENTO,RM.CREDITO ,RM.RETE_INVA,RM.NO_DEDUC ,RM.IVA_MAY
) AS D
) AS E
WHERE E.VALOR+E.RETENCION_F+E.RETE_IVA_F+E.NO_DEDUC_F+E.IVA_MAY_F<>0
ORDER BY E.NIT


