

SELECT P.CONCEPTO,TM.TIPO,TM.NIT,TM.DIGITO,TM.PAPELLIDO,TM.SAPELLIDO,TM.PNOMBRE,TM.SNOMBRE,TM.RAZON_SOCIAL,TM.PAIS,SUM(P.VALOR) VALOR,SUM(ISNULL(DM.VALOR,0)) DEVOLUCION
FROM (

SELECT CF.CONCEPTO CONCEPTO,
CASE WHEN (ROUND(SUM(CV.saldo_inicial+CV.debito-CV.credito),0)*-1)<500000 THEN 222222222 ELSE TR.NIT END NIT,
ROUND(SUM(CV.saldo_inicial+CV.debito-CV.credito),0)*-1 VALOR
FROM cuentas_val CV 
INNER JOIN cuentas_formatos CF ON (CV.cuenta=CF.cuenta)
INNER JOIN terceros T ON (CV.nit=T.nit)
INNER JOIN terceros TR ON (T.nit_real=TR.nit)

WHERE CF.formato=1007 AND CV.ano=2015 AND CV.mes=12
GROUP BY  CF.formato ,CF.concepto ,TR.NIT
HAVING ROUND(SUM(CV.saldo_inicial+CV.debito-CV.credito),0)<>0) AS P
LEFT JOIN terceros_medios TM ON (P.NIT=TM.NIT)
LEFT JOIN devoluciones_medios DM ON (P.NIT=DM.nit AND P.CONCEPTO=4001)
GROUP BY P.CONCEPTO,TM.TIPO,TM.NIT,TM.DIGITO,TM.PAPELLIDO,TM.SAPELLIDO,TM.PNOMBRE,TM.SNOMBRE,TM.RAZON_SOCIAL,TM.PAIS
ORDER BY CONCEPTO
