SELECT TM.TIPO,TM.NIT,TM.DIGITO,TM.PAPELLIDO,TM.SAPELLIDO,TM.PNOMBRE,TM.SNOMBRE,TM.RAZON_SOCIAL,PAIS,SUM(P.VALOR) VALOR
FROM (

SELECT CF.CONCEPTO CONCEPTO,
 T.NIT  NIT,
ROUND(SUM(CV.saldo_inicial+CV.debito-CV.credito),0) VALOR
FROM cuentas_val CV 
INNER JOIN cuentas_formatos CF ON (CV.cuenta=CF.cuenta)
LEFT JOIN bancos B ON (CV.cuenta=B.cuenta)
LEFT JOIN terceros T ON (B.nit_banco=T.nit)
WHERE CF.formato=1012 AND CV.ano=2015 AND CV.mes=12
GROUP BY  CF.formato ,CF.concepto ,T.NIT,CV.cuenta
HAVING ROUND(SUM(CV.saldo_inicial+CV.debito-CV.credito),0)<>0) AS P
LEFT JOIN terceros_medios TM ON (P.NIT=TM.NIT)

GROUP BY P.CONCEPTO,TM.TIPO,TM.NIT,TM.DIGITO,TM.PAPELLIDO,TM.SAPELLIDO,TM.PNOMBRE,TM.SNOMBRE,TM.RAZON_SOCIAL,TM.PAIS,TM.DIRECCION,TM.CIUDAD,TM.DEPARTAMENTO
ORDER BY CONCEPTO
