SELECT P.CONCEPTO,TM.TIPO,TM.NIT,TM.DIGITO,TM.PAPELLIDO,TM.SAPELLIDO,TM.PNOMBRE,TM.SNOMBRE,TM.RAZON_SOCIAL,TM.PAIS,SUM(P.VALOR)*-1 VALOR,
TM2.TIPO TIPOBEN,TM2.NIT NITBEN,TM2.PAPELLIDO,TM2.SAPELLIDO,TM2.PNOMBRE,TM2.SNOMBRE,TM2.RAZON_SOCIAL,TM2.DIRECCION,TM2.DEPARTAMENTO,
TM2.CIUDAD,TM2.PAIS
FROM (

SELECT CF.CONCEPTO CONCEPTO,CV.cuenta CUENTA,
 T.NIT  NIT2,TR.nit NIT ,
 CASE 
 WHEN T.nombres LIKE '%DEPARTAMENTO%' OR T.nombres LIKE  '%GOBERNACION%' THEN T.nit
 WHEN CV.cuenta IN ('24440501','24440503') THEN SM.Nit 
 WHEN CV.cuenta IN ('28150501') THEN 800067604
 WHEN CV.cuenta IN ('24440502') THEN 899999090 ELSE 0 END NIT_BEN,
ROUND(SUM(CV.valor),0) VALOR
FROM movimiento CV 
INNER JOIN cuentas_formatos CF ON (CV.cuenta=CF.cuenta)
INNER JOIN terceros T ON (CV.nit=T.nit)
INNER JOIN terceros TR ON (T.nit_real=TR.nit)
LEFT JOIN SobretasaMunicipios SM ON (T.y_dpto+T.y_ciudad=SM.CodDane)
WHERE CF.formato=1647 AND YEAR(CV.fec)=2015 AND CV.tipo<>'Z1' AND NOT (CV.tipo='AJT' AND CV.numero=2033) AND CV.valor<0
GROUP BY  CF.formato ,CF.concepto ,T.nit,CV.cuenta,SM.Nit,TR.nit,T.nombres
HAVING ROUND(SUM(CV.valor),0)<>0) AS P
LEFT JOIN terceros_medios TM ON (P.NIT=TM.NIT)
LEFT JOIN terceros_medios TM2 ON (P.NIT_BEN=TM2.NIT)
GROUP BY P.CONCEPTO,TM.TIPO,TM.NIT,TM.DIGITO,TM.PAPELLIDO,TM.SAPELLIDO,TM.PNOMBRE,TM.SNOMBRE,TM.RAZON_SOCIAL,TM.PAIS,TM.DIRECCION,TM.CIUDAD,TM.DEPARTAMENTO,
TM2.TIPO ,TM2.NIT ,TM2.PAPELLIDO,TM2.SAPELLIDO,TM2.PNOMBRE,TM2.SNOMBRE,TM2.RAZON_SOCIAL,TM2.DIRECCION,TM2.DEPARTAMENTO,
TM2.CIUDAD,TM2.PAIS
ORDER BY TM.NIT