DECLARE @AAÑO AS INTEGER=YEAR(GETDATE())
DECLARE @MMES AS INTEGER =MONTH(GETDATE())
DECLARE @ADIAS AS INTEGER=DAY(GETDATE())
DECLARE @CONT AS INTEGER=0
DECLARE @VAR AS INTEGER=0
DECLARE @COD_VEN AS DECIMAL(18,0)
DECLARE @PTOTAL AS NVARCHAR(MAX)
DECLARE @ENCABEZADO AS NVARCHAR(MAX)
DECLARE @TABLAHTML AS NVARCHAR(MAX)
DECLARE @ASUNTO AS VARCHAR(MAX)

SET @ENCABEZADO=
N'<style>
td, th {
    font-size: 75%;
    font-family: "Trebuchet MS";
}</style>'

SET @ASUNTO=(SELECT 'ZEUSS: Ventas diarias combustible a ' + DATENAME(MM,GETDATE()) + ' ' + CAST(DAY(GETDATE()) AS VARCHAR(10)) + ' de ' + CAST(YEAR(GETDATE()) AS VARCHAR(20)));
--VENTAS GIRARDOTA	

		DECLARE SEST CURSOR

		FOR 
		
			SELECT V.COD_VEN
			FROM ventas_total_mes_vendedor V 
			WHERE V.AÑO=@AAÑO AND V.MES=@MMES AND COD_VEN<>999999
			ORDER BY V.COD_VEN
			
		OPEN SEST

			FETCH NEXT FROM SEST INTO @COD_VEN
			
	
			
		WHILE @@FETCH_STATUS = 0  
		BEGIN 
				
				

							
				EXEC spVentasDiarias_Asesor 
				@CORREO='jballesteros@zeuss.com.co',
				@AÑO=@AAÑO,
				@MES=@MMES,
				@DIA=@ADIAS,
				@ASESOR=@COD_VEN
	
			
				
				FETCH NEXT FROM SEST INTO @COD_VEN
				
		END	




		CLOSE SEST

		DEALLOCATE SEST






