SELECT Q.CONCEPTO,TM.TIPO,ISNULL(TM.NIT,Q.NIT) NIT,TM.DIGITO,TM.PAPELLIDO,TM.SAPELLIDO,TM.PNOMBRE,TM.SNOMBRE,TM.RAZON_SOCIAL,TM.PAIS,SUM(Q.K) K,0 L,0 M,0 N,0 O ,0 P,SUM(Q.Q) Q
FROM (


SELECT C.CONCEPTO,CASE WHEN C.K+C.Q <500000 THEN 222222222 ELSE NIT END NIT,C.K,C.Q
FROM (

SELECT T.CONCEPTO,T.NIT,SUM(K) K, SUM (Q) Q
FROM (


SELECT *
FROM (


SELECT CONCEPTO,NIT,SUM(K) K,0 Q
FROM (


SELECT 
CASE 
WHEN CV.cuenta BETWEEN '4135' AND '4135zzzzzz'   THEN 4001
WHEN CV.cuenta BETWEEN '421040' AND '4295zzzzzz' THEN 4002
WHEN CV.cuenta BETWEEN '421005' AND '421005' THEN 4003

ELSE 0 END CONCEPTO,T.nit_real NIT,
 ROUND((saldo_inicial+debito-credito)*-1,0) K
FROM cuentas_val CV INNER JOIN terceros T ON (CV.nit=T.nit)
WHERE CV.ano=2016 AND CV.mes=12 AND 
(
CV.cuenta LIKE '4%' )


)

AS P

GROUP BY CONCEPTO,NIT
HAVING SUM( K)<>0



) AS S 




) AS T

GROUP BY T.CONCEPTO,T.NIT


) C ) AS Q left JOIN terceros_medios TM ON (Q.NIT=TM.NIT)

GROUP BY Q.CONCEPTO,Q.NIT,TM.TIPO,TM.NIT,TM.DIGITO,TM.PAPELLIDO,TM.SAPELLIDO,TM.PNOMBRE,TM.SNOMBRE,TM.RAZON_SOCIAL,TM.PAIS

ORDER BY CONCEPTO,NIT