DECLARE @FECHAUNO AS DATE='01/05/2015'
DECLARE @FECHADOS AS DATE='31/05/2015'
DECLARE @FECHATRES AS DATE='26/04/2015'
DECLARE @FECHACUATRO AS DATE='25/05/2015'

SELECT D.tipo TIPO,D.numero NUMERO, D.NOTAS NOTAS,D.nit NIT,T.nombres CLIENTE,D.fecha FECHA,D.valor_total VALOR,S.BONIFICACION,S.BONIFICACIONMAX
FROM documentos D 
INNER JOIN terceros T ON (D.nit=T.nit)
INNER JOIN (SELECT *
FROM (
SELECT T.nit,T.nombres,SUM(ZA.BONIFICACION) BONIFICACION,SUM(ZA.BONIFICACIONMAX) BONIFICACIONMAX
FROM Zeuss_BonificacionAgrup ZA INNER JOIN terceros T ON (ZA.nit=T.nit)
WHERE vencimiento BETWEEN @FECHATRES AND @FECHACUATRO
GROUP BY T.nit,T.nombres
HAVING SUM(ZA.DESCUENTOCL)<>0
UNION
SELECT T.nit,T.nombres,SUM(ZA.BONIFICACION) BONIFICACION,SUM(ZA.BONIFICACIONMAX) BONIFICACIONMAX
FROM Zeuss_BonificacionAgrup ZA INNER JOIN terceros T ON (ZA.NIT_REAL=T.nit)
WHERE vencimiento BETWEEN @FECHATRES AND @FECHACUATRO
GROUP BY T.nit,T.nombres
HAVING SUM(ZA.DESCUENTOCL)<>0) AS P) AS S ON (S.nit=T.nit)
WHERE tipo='NC' AND concepto=51 and fecha BETWEEN @FECHAUNO AND @FECHADOS AND D.anulado=0
ORDER BY  T.nit