DROP TABLE comisiones_nuevas_vendedor

SELECT S.COD_VEN,S.VENDEDOR,S.COD_CLIENTE,S.CLIENTE,S.PRODUCTO,S.CANTIDAD,SUM(COMISION) COMISION
--INTO comisiones_nuevas_vendedor
FROM (



SELECT AÑO,MES,P.COD_VEN,P.VENDEDOR,P.COD_CLIENTE,P.CLIENTE,P.PRODUCTO,P.CANTIDAD, 


CASE WHEN DESCUENTO>=menor AND DESCUENTO<=mayor THEN 
	(CASE WHEN NIT_REAL=900625898 AND COD_VEN=118 THEN 1.5*CANTIDAD 
		WHEN NIT_REAL=900625898 AND COD_VEN=133 THEN 0.5*CANTIDAD 
		WHEN COD_VEN=109 AND COSTO_LOGISTICO<>0 THEN COSTO_LOGISTICO*CANTIDAD  
		ELSE V.PESOS*CANTIDAD END) ELSE 0 END  COMISION
		
		
		
FROM (


SELECT ZL.ano AÑO,ZL.mes MES,TV.nit COD_VEN,TV.nombres VENDEDOR,T.nit COD_CLIENTE,T.nombres CLIENTE,RS.descripcion PRODUCTO,SUM(ZL.can_real) CANTIDAD,VM.margen MARGEN,
ROUND((

CASE WHEN ISNUMERIC(ISNULL(T.concepto_8,''))=0 THEN 0 ELSE CAST(T.concepto_8 AS REAL) END)  + 

(VM.margen*(CASE WHEN ISNUMERIC(ISNULL(T.concepto_9,''))=0 THEN 0 ELSE CAST(T.concepto_9 AS REAL)  END)/100)),2) DESCUENTO,T.nit_real NIT_REAL,

CASE 
		WHEN CAST(ISNULL(T.concepto_7,0) AS REAL)*0.3>0  AND CAST(ISNULL(T.concepto_7,0) AS REAL)*0.3<=40 THEN 8
		WHEN CAST(ISNULL(T.concepto_7,0) AS REAL)*0.3>40  AND CAST(ISNULL(T.concepto_7,0) AS REAL)*0.3<=81 THEN 10
		WHEN CAST(ISNULL(T.concepto_7,0) AS REAL)*0.3>81 THEN 15 ELSE 0 END COSTO_LOGISTICO



FROM Zeuss_Lin_Ventas ZL
INNER JOIN terceros T ON (ZL.nit=T.nit)
INNER JOIN terceros TV ON (T.vendedor=TV.nit)
INNER JOIN referencias_sub2 RS ON (ZL.subgrupo2=RS.subgrupo2)
CROSS JOIN v_margen_mayorista VM 
WHERE ZL.subgrupo2 IN (2,3,4) AND YEAR(ZL.fec)>=2017

GROUP BY ZL.ano,ZL.mes,T.nit,T.nombres,RS.descripcion,TV.nit,TV.nombres,VM.margen,T.concepto_9,T.concepto_8,T.nit_real,T.concepto_7

) AS P INNER JOIN v_vendedor_comision V ON (P.COD_VEN=V.vendedor)

)  AS  S

GROUP BY  S.AÑO,S.MES,S.COD_VEN,S.VENDEDOR,S.COD_CLIENTE,S.CLIENTE,S.PRODUCTO,S.CANTIDAD
ORDER BY PRODUCTO