drop view v_nom_autoliquidacion_nit
drop view v_nom_autoliquidacion_ingresos
drop view v_nom_autoliquidacion_retiros
drop view v_nom_autoliquidacion_mes_completo
drop view v_nom_autoliquidacion_unificar
drop view v_nom_autoliquidacion_nit_unificar_decreto_2388
drop view v_nom_autoliquidacion_total_fondos_arp
drop view v_nom_autoliquidacion_total_fondos_parafiscal
drop view v_nom_autoliquidacion_total_fondos_pension
drop view v_nom_autoliquidacion_total_fondos_salud
drop view v_nom_autoliquidacion_total_secuencia
drop view v_nom_autoliquidacion_resumen_cajas
drop view v_nom_autoliquidacion_resumen_fondos_arp
drop view v_nom_autoliquidacion_resumen_fondos_pension
drop view v_nom_autoliquidacion_resumen_fondos_salud


