

DECLARE @CONSULTA AS VARCHAR(MAX)=NULL
DECLARE @RUTA AS VARCHAR(MAX)=NULL
DECLARE @COMANDO AS VARCHAR(MAX)=NULL

SET @RUTA='C:\dms_con\dmssql\report\Planos\Informe_Cesar' + CONVERT(VARCHAR,GETDATE(),6) + '.txt' 
 
SET @CONSULTA=N'SELECT 811043174,1,50,AÑO,' +
N'CASE WHEN MES<10 THEN ''''0'''' + CAST(MES AS VARCHAR)' +
N'ELSE CAST(MES AS VARCHAR) END,5001,DOCUMENTO,FECHA,TIPO,NIT,RAZON_COMERCIAL,EDS,CLASE,CAST(GALONES AS INTEGER),CAST(VALOR AS INTEGER),CAST(PALCOHOL AS INTEGER), '+
N'CAST(ROUND(GALONES * VALOR * ((100-PALCOHOL)/100),0) AS INTEGER),CAST(0.065 AS VARCHAR),CAST(ROUND(CAST(ROUND(GALONES * VALOR * ((100-PALCOHOL)/100),0) AS INTEGER)*0.065,0) AS INTEGER)'+
N'FROM ZEUSS.DBO.V_Informe_Cesar WHERE AÑO=2016 AND MES=8'

SET @COMANDO='EXEC xp_cmdshell ''bcp "' + @CONSULTA + '" queryout "' + @RUTA + '" -T -c -t;'''


PRINT @COMANDO

EXEC (@COMANDO)