DECLARE @TIPO AS VARCHAR(20)='VC2'
DECLARE @NUMERO AS INTEGER=7944
DECLARE @ASESOR AS DECIMAL(18,0)=244


UPDATE documentos
SET vendedor=@ASESOR
WHERE tipo=@TIPO AND numero=@NUMERO

UPDATE documentos_lin
SET vendedor=@ASESOR
WHERE tipo=@TIPO AND numero=@NUMERO