DECLARE @NUMINF AS INTEGER=235183
DECLARE @NUMSUP AS INTEGER=235183
DECLARE @FECHA AS DATE='29/01/2017'

UPDATE documentos 
SET fecha=@FECHA
WHERE tipo='RC' AND numero BETWEEN @NUMINF AND @NUMSUP


UPDATE movimiento
SET fec=@FECHA
WHERE tipo='RC' AND numero BETWEEN @NUMINF AND @NUMSUP