DECLARE @FECHA AS DATE
DECLARE @AÑO AS INTEGER
DECLARE @MES AS INTEGER
DECLARE @DIA AS INTEGER
DECLARE @NIT AS DECIMAL(18,0)
DECLARE @SALDO AS MONEY
DECLARE @DEBITO AS MONEY
DECLARE @CREDITO AS MONEY
DECLARE @NSALDO AS MONEY
DECLARE @SALDOF AS MONEY
DECLARE @NITA AS DECIMAL(18,0)

DECLARE SEST CURSOR

FOR 

 
SELECT *
FROM Prepagagos_Contab



OPEN SEST

 FETCH NEXT FROM SEST INTO @FECHA,@AÑO,@MES,@DIA,@NIT,@SALDO,@DEBITO,@CREDITO,@NSALDO
 SET @SALDOF=@SALDO+@DEBITO-@CREDITO
 
 
 
 UPDATE Prepagagos_Contab
 SET  NSALDO=@SALDOF
 WHERE FECHA=@FECHA
		


 WHILE @@FETCH_STATUS = 0  
    BEGIN 
		 FETCH NEXT FROM SEST INTO @FECHA,@AÑO,@MES,@DIA,@NIT,@SALDO,@DEBITO,@CREDITO,@NSALDO
		
			UPDATE Prepagagos_Contab
			SET SALDO=@SALDOF, 
			AÑO=YEAR(FECHA),MES=MONTH(FECHA),
			DIA=(DAY(FECHA)),DEBITO=ISNULL(@DEBITO,0),CREDITO=ISNULL(@CREDITO,0)
			WHERE FECHA=@FECHA
	
		    SET @SALDOF=@SALDOF+ISNULL(@DEBITO,0)-ISNULL(@CREDITO,0)
		
			update Prepagagos_Contab
			SET NSALDO=@SALDOF
			WHERE FECHA=@FECHA
	END	
	
	 CLOSE SEST
 
 DEALLOCATE SEST
