CREATE TRIGGER tgEnviarCorreo
   ON  referencias
   AFTER INSERT
AS 
BEGIN
	DECLARE @CODIGO AS VARCHAR(20)
	DECLARE @DESCRIPCION AS VARCHAR(80)
	DECLARE @CLASE AS  VARCHAR(10)
	DECLARE @GRUPO AS VARCHAR(10)
	DECLARE @SUBGRUPO AS VARCHAR(10)
	
	
	SELECT @CODIGO=I.CODIGO,
	@DESCRIPCION=I.DESCRIPCION,
	@CLASE=I.CLASE,
	@GRUPO=I.GRUPO,
	@SUBGRUPO=I.SUBGRUPO
	FROM INSERTED I 
	LEFT JOIN REFERENCIAS_CLASE RC ON (I.CLASE=RC.CLASE)
	LEFT JOIN REFERENCIAS_GRUPO RG ON (I.GRUPO=RG.GRUPO)
	LEFT JOIN REFERENCIAS_SUBGRUPO RS ON (I.GRUPO=RS.GRUPO AND I.SUBGRUPO=RS.SUBGRUPO)
	
	
	
	

END
GO
