DECLARE @AÑO AS INTEGER=2016
DECLARE @MES AS INTEGER=11
DECLARE @BODEGA AS INTEGER=4
DECLARE @NITINF AS DECIMAL(18,0)=1
DECLARE @NITSUP AS DECIMAL(18,0)=999999999
DECLARE @CNIT AS INTEGER
DECLARE @I AS INTEGER=0
DECLARE @NIT AS DECIMAL(18,0)
DECLARE @FECHAC AS DATE
DECLARE @AÑOC AS INTEGER
DECLARE @MESC AS INTEGER
DECLARE @DIAC AS INTEGER
DECLARE @NITC AS DECIMAL(18,0)
DECLARE @SALDO AS MONEY
DECLARE @DEBITO AS MONEY
DECLARE @CREDITO AS MONEY
DECLARE @NSALDO AS MONEY
DECLARE @SALDOF AS MONEY
DECLARE @NITA AS DECIMAL(18,0)
DECLARE @BODEGAC AS INTEGER
DECLARE @SALDOC AS MONEY
DECLARE @DEBITOC AS MONEY
DECLARE @CREDITOC AS MONEY

DELETE FROM Prepagados_tmp_01
DELETE FROM Prepagados_Contable

INSERT INTO Prepagados_tmp_01
SELECT  ROW_NUMBER() OVER (ORDER BY SP.NIT ) ID,SP.NIT
FROM saldos_prepagados_02 SP 
WHERE SP.AÑO=@AÑO AND SP.MES=@MES AND 
bodega=@BODEGA AND SP.NIT BETWEEN @NITINF AND @NITSUP
GROUP BY SP.NIT

SELECT @CNIT=COUNT(NIT)
FROM Prepagados_tmp_01

WHILE @I<=@CNIT-1
BEGIN
	SELECT @NIT=NIT
	FROM Prepagados_tmp_01
	WHERE ID=@I+1
	
	DELETE FROM Prepagados_tmp_02
	
	
	INSERT INTO Prepagados_tmp_02
	SELECT P.fecha FECHA,T.AÑO,T.MES,T.DIA,T.NIT,T.SALDO,T.DEBITO,T.CREDITO,@BODEGA,0
	FROM (


	SELECT fecha
	FROM y_calendario
	WHERE YEAR(fecha)=@AÑO AND MONTH(fecha)=@MES) AS P 

	LEFT JOIN (

	SELECT *
	FROM saldos_prepagados_02
	where AÑO=@AÑO AND MES=@MES AND NIT=@NIT AND BODEGA=@BODEGA) AS T ON (P.fecha=T.fecha)

	
	
	
	DECLARE SEST CURSOR
	
	FOR 

 
	SELECT *
	FROM Prepagados_tmp_02

	ORDER BY FECHA
	
	OPEN SEST

	FETCH NEXT FROM SEST INTO @FECHAC,@AÑOC,@MESC,@DIAC,@NITC,
	@SALDOC,@DEBITOC,@CREDITOC,@BODEGAC,@NSALDO
	SET @SALDOF=ISNULL(@SALDOC,0)+ISNULL(@DEBITOC,0)-ISNULL(@CREDITOC,0)

	UPDATE Prepagados_tmp_02
	SET  NSALDO=@SALDOF
	WHERE FECHA=@FECHAC	


	WHILE @@FETCH_STATUS = 0  
    BEGIN 
		 	FETCH NEXT FROM SEST INTO @FECHAC,@AÑOC,@MESC,@DIAC,@NITC,
			@SALDOC,@DEBITOC,@CREDITOC,@BODEGAC,@NSALDO
		
			UPDATE Prepagados_tmp_02
			SET SALDO=@SALDOF, 
			AÑO=YEAR(FECHA),MES=MONTH(FECHA),
			DIA=(DAY(FECHA)),DEBITO=ISNULL(@DEBITOC,0),CREDITO=ISNULL(@CREDITOC,0),NIT=@NIT
			WHERE FECHA=@FECHAC 	
	
		    SET @SALDOF=@SALDOF+ISNULL(@DEBITOC,0)-ISNULL(@CREDITOC,0)
		
			update Prepagados_tmp_02
			SET NSALDO=@SALDOF
			WHERE FECHA=@FECHAC	
	END	
	
	
	
	
	 CLOSE SEST
 
 DEALLOCATE SEST


	INSERT INTO Prepagados_Contable
	SELECT *
	FROM Prepagados_tmp_02

	SET @I=@I+1

END

