USE [ryrlub]
GO

/****** Object:  Trigger [dbo].[AFI_INS_Auditoria]    Script Date: 08/02/2018 03:17:52 p. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

ALTER TRIGGER [dbo].[AFI_INS_Auditoria]
   ON  [dbo].[auditoria]
   AFTER INSERT 
AS 
BEGIN

	DECLARE @TIPO AS VARCHAR(4)
	DECLARE @NUMERO AS INTEGER
	DECLARE @QUE AS VARCHAR(255)
	DECLARE @ID AS INTEGER

	SELECT @QUE=QUE,@ID=ID
	FROM INSERTED

	IF @QUE NOT  LIKE 'Anuló documento%'
	BEGIN
		RETURN
	END

	SELECT 
	@TIPO=SUBSTRING( SUBSTRING(@QUE,17, CHARINDEX(',',@QUE,0)-17),0,   CHARINDEX(' ',  SUBSTRING(@QUE,17, CHARINDEX(',',@QUE,0)-17),0)) ,
	@NUMERO=  SUBSTRING(  SUBSTRING(@QUE,17, CHARINDEX(',',@QUE,0)-17),CHARINDEX(' ',  SUBSTRING(@QUE,17, CHARINDEX(',',@QUE,0)-17),0)+1,LEN(  SUBSTRING(@QUE,17, CHARINDEX(',',@QUE,0)-17))-CHARINDEX(' ',  SUBSTRING(@QUE,17, CHARINDEX(',',@QUE,0)-17),0))


	UPDATE auditoria 
	SET TIPO=@TIPO, NUMERO=@NUMERO
	WHERE ID=@ID






END
GO


