DECLARE @AAÑO AS INTEGER
DECLARE @AMES AS INTEGER
DECLARE @ADIA AS INTEGER
DECLARE @MAXDIA AS INTEGER=(SELECT MAX(DAY(FECHA))
FROM interfaz_control_dias
WHERE YEAR(fecha)=YEAR(GETDATE()) AND MONTH(fecha)=MONTH(GETDATE()))



IF  @MAXDIA IS NULL
BEGIN 
	SET @AAÑO=YEAR(DATEADD(D,-1,GETDATE()))
	SET @AMES=MONTH(DATEADD(D,-1,GETDATE()))
	SET @ADIA=DAY(DATEADD(D,-1,GETDATE()))
END
ELSE IF @MAXDIA IS NOT NULL
BEGIN
	SET @AAÑO=YEAR(GETDATE())
	SET @AMES=MONTH(GETDATE())
	SET @ADIA=DAY(GETDATE())
END

	exec  spventasdiarias2 
	@CORREO='marcela.ocampo@zeusspetroleum.com',
	@AÑO=@AAÑO,
	@MES=@AMES,
	@DIA=@ADIA