SELECT TIPON TIPO,nit NIT,
CASE WHEN TIPON=13 THEN '' ELSE CAST(digito AS VARCHAR(2)) END DIGITO,
CASE WHEN TIPON=13 AND ESPACIOS>0 THEN  SUBSTRING(NOMBRES,0,PESP) 
	 WHEN TIPON=13 AND ESPACIOS=0 THEN NOMBRES  ELSE '' END PAPELLIDO,
CASE WHEN TIPON=13 AND ESPACIOS>1 THEN  SUBSTRING(NOMBRES,PESP+1,SESP-PESP-1) 
						 ELSE '' END SAPELLIDO,
CASE WHEN TIPON=13 AND ESPACIOS>2 THEN  SUBSTRING(NOMBRES,SESP+1,TESP-SESP-1) 
	 WHEN TIPON=13 AND ESPACIOS=2 THEN	SUBSTRING(NOMBRES,SESP+1 ,LEN(NOMBRES))				
	 WHEN TIPON=13 AND ESPACIOS=1 THEN  SUBSTRING(NOMBRES,PESP+1 ,LEN(NOMBRES))	ELSE '' END PNOMBRE,
CASE WHEN TIPON=13 AND ESPACIOS>2 THEN  SUBSTRING(NOMBRES,TESP+1,LEN(NOMBRES)) ELSE '' END SNOMBRE,

CASE WHEN TIPON=31 THEN NOMBRES ELSE '' END RAZONSOCIAL,IVA SALDOFINAL,IVA_DEV DEVOLUCION



FROM (
SELECT 
CASE WHEN TIPO='C' THEN 13 ELSE 31 END TIPON,
 *,DBO.CUENTA_ESPACIOS(NOMBRES) ESPACIOS,
CHARINDEX(' ',NOMBRES,0) PESP,
CHARINDEX(' ',NOMBRES,CHARINDEX(' ',NOMBRES,0) +1) SESP,
CHARINDEX(' ',NOMBRES,CHARINDEX(' ',NOMBRES,CHARINDEX(' ',NOMBRES,0) +1)+1) TESP

 
FROM (
SELECT TR.nit,TR.digito,TR.tipo_identificacion TIPO,
RTRIM(
UPPER(
REPLACE(
CASE WHEN CHARINDEX('/', TR.nombres,0)=0 THEN TR.nombres ELSE  SUBSTRING(TR.NOMBRES,0, CHARINDEX('/', TR.nombres,0)) END
,'.',''))) NOMBRES,

SUM(CASE WHEN CV.cuenta IN ('24081001',
'24081002',
'24081003',
'24081004',
'24081006') AND CV.mes=12 AND TR.nit<>13 THEN  saldo_inicial+debito-credito ELSE 0 END ) IVA,
SUM(CASE WHEN CV.cuenta IN ('24081005') AND MES<>13 THEN  debito-credito ELSE 0 END ) IVA_DEV

FROM cuentas_val CV 
INNER JOIN terceros T ON (CV.nit=T.nit)
INNER JOIN terceros TR ON (T.nit_real=TR.nit)
WHERE CV.ano=2015 AND cuenta IN ('24081001',
'24081002',
'24081003',
'24081004',
'24081006',
'24081005')
GROUP BY TR.nit,TR.nombres,TR.digito,TR.tipo_identificacion) AS F
WHERE (F.IVA+F.IVA_DEV)<>0) AS F1005
ORDER BY F1005.nit