SELECT CONCEPTO,

CASE WHEN TIPO='C' THEN 13 ELSE 31 END TIPO,F.nit NIT,CASE WHEN TIPO='C' THEN CAST(DIGITO AS VARCHAR(2)) ELSE '' END DIGITO,
CASE WHEN TIPO='C' THEN NOMBRES ELSE '' END NOMBRES,
CASE WHEN TIPO<>'C' THEN NOMBRES ELSE '' END RAZON_SOCIAL,
PAIS,
F.VALOR,
ISNULL(DM.VALOR,0) VALOR
FROM F1007 F LEFT JOIN devoluciones_medios DM ON (F.nit=DM.nit AND F.CONCEPTO=4001)
ORDER BY CONCEPTO,F.VALOR