SELECT FORMATO,TIPON,P.NIT,DIGITO,NOMBRES,RAZON_SOCIAL,DIRECCION,CIUDAD,DEPTO,PAIS,ROUND(SUM(P.VALOR),0) VALOR
 FROM (

SELECT 
CASE WHEN M.cuenta BETWEEN '2205' AND '2205' THEN 2201
		WHEN M.cuenta BETWEEN '2355' AND '2356' THEN 2202
		WHEN M.cuenta BETWEEN '2105' AND '212015' THEN 2203
		WHEN M.cuenta BETWEEN '25' AND '26'   THEN 2205

			WHEN M.cuenta  BETWEEN '2335' AND '233595'  OR
M.cuenta BETWEEN '2195' AND '2196'  THEN 2206
			ELSE 0 END FORMATO

,
CASE WHEN TR.tipo_identificacion='C' THEN 13 ELSE 31 END TIPON,
TR.nit NIT,
CASE WHEN TR.tipo_identificacion='C' THEN '' ELSE CAST(TR.DIGITO AS VARCHAR(2)) END DIGITO,
UPPER(replace(CASE WHEN TR.tipo_identificacion='C' THEN TR.nombres ELSE '' END,'.','')) NOMBRES,
UPPER(replace(CASE WHEN TR.tipo_identificacion<>'C' THEN TR.nombres ELSE '' END,'.','')) RAZON_SOCIAL,
UPPER(TR.direccion) DIRECCION, TR.y_ciudad CIUDAD,TR.y_dpto DEPTO,TR.y_pais PAIS,
ROUND((M.saldo_inicial+M.debito-M.credito),0)*-1 VALOR
FROM cuentas_val M 
INNER JOIN terceros T ON (M.nit=T.nit)
INNER JOIN terceros TR ON (T.nit_real=TR.nit)

WHERE M.ano=2015 AND M.mes=12 AND 

(

M.cuenta BETWEEN '2205' AND '2205' OR

M.cuenta BETWEEN '2355' AND '2356' OR
M.cuenta BETWEEN '2105' AND '212015'  OR
M.cuenta BETWEEN '2335' AND '233595'  OR
M.cuenta BETWEEN '2195' AND '2196'  OR
M.cuenta BETWEEN '25' AND '26'  
)
AND (M.saldo_inicial+M.debito-M.credito)<>0) AS P



GROUP BY FORMATO,TIPON,P.NIT,DIGITO,NOMBRES,RAZON_SOCIAL,DIRECCION,CIUDAD,DEPTO,PAIS
HAVING ROUND(SUM(P.VALOR),0)<>0



