SET @TSQL='ACTUALIZA_SALDOS_DOCS'
		SET @RPTA =0
		BEGIN TRY
			BEGIN TRAN 	@TSQL
			SET @RPTA=0					
			COMMIT TRANSACTION
		END TRY			
		BEGIN CATCH
			ROLLBACK TRANSACTION @TSQL
			SET @RPTA=0
		END CATCH