DECLARE @AAÑO AS INTEGER=YEAR(GETDATE())
DECLARE @AMES AS INTEGER=MONTH(GETDATE())
DECLARE @ADIAS AS INTEGER=DAY(GETDATE())

EXEC spVentasDiarias
@CORREO='jballesteros@zeuss.com.co',
@AÑO=@AAÑO,
@MES=@AMES,
@DIA=@ADIAS