	DECLARE @TIPO AS VARCHAR(4)
	DECLARE @NUMERO AS INTEGER
	DECLARE @CUENTA AS VARCHAR(20)
	DECLARE @CENTRO AS INTEGER
	DECLARE @NIT AS DECIMAL(18,0)
	DECLARE @FEC AS DATE
	DECLARE @VALOR AS MONEY
	DECLARE @EXPLICACION AS VARCHAR(250)
	DECLARE @VALOR_NIIF AS MONEY
	DECLARE @SEQ AS INTEGER
	DECLARE @TSQL AS VARCHAR(250)
	DECLARE @RST AS VARCHAR
	
	SET @TSQL='ACTUALIZA_SALDOS_DOCS'
	SET @RST =0

	DECLARE ASMOVIMIENTO CURSOR


	FOR 

		SELECT tipo,numero,cuenta,centro,nit,fec,valor,explicacion,valor_niif
		FROM MOVIMIENTO12072018

	OPEN ASMOVIMIENTO

	FETCH NEXT FROM ASMOVIMIENTO INTO @TIPO,@NUMERO,@CUENTA,@CENTRO,@NIT,@FEC,@VALOR,@EXPLICACION,@VALOR_NIIF

		WHILE @@FETCH_STATUS = 0  
		BEGIN 
			BEGIN TRAN 	@TSQL

				BEGIN TRY

					SELECT @SEQ=MAX(seq)+1
					FROM movimiento
					WHERE tipo=@TIPO AND numero=@NUMERO AND seq<1000000

					INSERT INTO movimiento(tipo,numero,seq,cuenta,centro,nit,fec,valor,explicacion,valor_niif)
					VALUES (@TIPO,@NUMERO,@SEQ,@CUENTA,@CENTRO,@NIT,@FEC,@VALOR,@EXPLICACION,@VALOR_NIIF)

					SET @RST=1

					COMMIT TRANSACTION

				END TRY

				BEGIN CATCH					
			
					ROLLBACK TRANSACTION @TSQL
					SELECT ERROR_MESSAGE()
					SET @RST=0	

				END CATCH

				FETCH NEXT FROM ASMOVIMIENTO INTO @TIPO,@NUMERO,@CUENTA,@CENTRO,@NIT,@FEC,@VALOR,@EXPLICACION,@VALOR_NIIF	
					
			END			

					
					

		CLOSE ASMOVIMIENTO
		DEALLOCATE ASMOVIMIENTO