DECLARE @BODEGA AS INTEGER=1
DECLARE @AÑO AS INTEGER=2016
DECLARE @MES AS INTEGER=5


	DELETE 
	FROM MOVIMIENTO 
	FROM MOVIMIENTO M 
		INNER JOIN DOCUMENTOS D ON (M.TIPO=D.TIPO AND M.NUMERO=D.NUMERO)
	WHERE BODEGA=@BODEGA AND YEAR(D.FECHA)=@AÑO AND MONTH(D.FECHA)=@MES AND M.SEQ>=1000000
	
	DELETE FROM movimiento
    FROM documentos D INNER JOIN movimiento M ON (D.tipo=M.tipo AND D.numero=M.numero)
     WHERE D.anulado=1 AND YEAR(D.FECHA)=@AÑO AND MONTH(D.FECHA)=@MES