DECLARE @CUENTA_ING AS VARCHAR(20)='41351004'
DECLARE @CUENTA VARCHAR(20)='61351004'
DECLARE @AÑO AS INTEGER=2016
DECLARE @MES AS INTEGER=4
DECLARE @BODEGA AS INTEGER=1
DECLARE @CENTROINF AS INTEGER=(@BODEGA*100)-100
DECLARE @CENTROMAY AS INTEGER=@CENTROINF+99




SELECT *,ROUND(isnull(P.COSTO,0)-isnull(T.VALOR,0),0) DIFERENCIA
FROM (
SELECT  tipo,numero,SUM(valor_unitario*cantidad) COSTO
FROM v_estinsa_lin_ventas_reclasificacion
WHERE ano=@AÑO AND mes=@MES AND bodega=@BODEGA and  IDSUBCONTABLE=@CUENTA AND IDSW=1
GROUP BY tipo,numero) AS P FULL JOIN
(

SELECT tipo,numero,SUM(valor)*-1  VALOR
FROM movimiento
where cuenta=@CUENTA_ING and centro between @CENTROINF and @CENTROMAY and YEAR(fec)=@AÑO and MONTH(fec)=@MES
GROUP BY tipo,numero) AS T ON (P.tipo=T.tipo AND P.numero=T.numero)
WHERE ROUND(P.COSTO-ISNULL(T.VALOR,0),0)<>0 OR P.COSTO IS NULL
ORDER BY DIFERENCIA DESC