DECLARE @CUENTA AS VARCHAR(20)='61350401'
DECLARE @AÑO AS INTEGER=2016
DECLARE @MES AS INTEGER=3
DECLARE @BODEGA AS INTEGER=4
DECLARE @CENTROINF AS INTEGER=301
DECLARE @CENTROMAY AS INTEGER=399




SELECT *,ROUND(P.COSTO-T.VALOR,0) DIFERENCIA
FROM (
SELECT  tipo,numero,SUM(costo_unitario*cantidad) COSTO
FROM v_estinsa_lin_ventas_reclasificacion
WHERE ano=@AÑO AND mes=@MES AND bodega=@BODEGA and  IDSUBCONTABLE=@CUENTA AND IDSW=1
GROUP BY tipo,numero) AS P FULL JOIN
(

SELECT tipo,numero,SUM(valor)  VALOR
FROM movimiento
where cuenta=@CUENTA and centro between @CENTROINF and @CENTROMAY and YEAR(fec)=@AÑO and MONTH(fec)=@MES
GROUP BY tipo,numero) AS T ON (P.tipo=T.tipo AND P.numero=T.numero)
WHERE ROUND(P.COSTO-ISNULL(T.VALOR,0),0)<>0 
ORDER BY DIFERENCIA DESC