DECLARE @AÑO AS INTEGER
DECLARE @MES AS INTEGER
DECLARE @CUANTIA AS MONEY
SET @AÑO=2012
SET @MES=12
SET @CUANTIA=0
SELECT *
FROM (
SELECT C.CONCEPTO,
CASE WHEN C.TERCERO='CUANTIAS MENORES' THEN 43 ELSE
CASE WHEN C.TIPO='C' THEN 13 ELSE
CASE WHEN C.TIPO='N' THEN 31 ELSE
CASE WHEN C.TIPO='T' THEN 12 ELSE 0 END END END END TIPO,
C.NIT  NIT,
 ' ' ELSE 
 DV,
CASE WHEN C.TIPO IN ('C','T') AND C.TERCERO<>'CUANTIAS MENORES' THEN SUBSTRING(C.TERCERO,1,C.PRIMERESPACIO-1) ELSE '' END PRIMERAPELLIDO,
CASE WHEN (C.SEGUNDOESPACIO=0 OR C.TERCERESPACIO=0) AND C.TIPO IN ('C','T') AND C.TERCERO<>'CUANTIAS MENORES' THEN '' ELSE
CASE WHEN C.TIPO IN ('C','T') AND C.TERCERO<>'CUANTIAS MENORES' THEN SUBSTRING(C.TERCERO,C.PRIMERESPACIO+1,(C.SEGUNDOESPACIO-C.PRIMERESPACIO)-1) ELSE '' END END SEGUNDOAPELLIDO,
CASE WHEN (C.TERCERESPACIO=0) AND C.TIPO IN ('C','T') AND C.TERCERO<>'CUANTIAS MENORES' THEN SUBSTRING(C.TERCERO,C.PRIMERESPACIO+1,(C.SEGUNDOESPACIO-C.PRIMERESPACIO)-1) ELSE 
CASE WHEN (C.SEGUNDOESPACIO=0) AND C.TIPO IN ('C','T') AND C.TERCERO<>'CUANTIAS MENORES' THEN SUBSTRING(C.TERCERO,C.PRIMERESPACIO+1,LEN(C.TERCERO)) ELSE  
CASE WHEN C.TIPO IN ('C','T') AND C.TERCERO<>'CUANTIAS MENORES' THEN SUBSTRING(C.TERCERO,C.SEGUNDOESPACIO+1,(C.TERCERESPACIO-C.SEGUNDOESPACIO-1)) ELSE '' END END END PRIMERNOMBRE,
CASE WHEN (C.TERCERESPACIO=0 OR C.SEGUNDOESPACIO=0) AND C.TIPO IN ('C','T') AND C.TERCERO<>'CUANTIAS MENORES' THEN SUBSTRING(C.TERCERO,C.SEGUNDOESPACIO+1,LEN(C.TERCERO)) ELSE 
CASE WHEN C.TIPO IN ('C','T') AND C.TERCERO<>'CUANTIAS MENORES' THEN SUBSTRING(C.TERCERO,C.TERCERESPACIO+1,LEN(C.TERCERO)) ELSE '' END END SEGUNDONOMBRE,
CASE WHEN C.TIPO='N' OR C.TERCERO='CUANTIAS MENORES' THEN C.TERCERO ELSE '' END RAZONSOCIAL,
CASE WHEN C.TERCERO='CUANTIAS MENORES' THEN 'ENTRADA A GIRARDOTA ANTIGUA ESTACION FERROCARRIL' ELSE C.DIRECCION END DIRECCION,
CASE WHEN C.TERCERO='CUANTIAS MENORES' THEN '05' ELSE C.CODDPTO END CODDPTO,
CASE WHEN C.TERCERO='CUANTIAS MENORES' THEN '308' ELSE C.CODCIUDAD END CODCIUDAD,
CASE WHEN C.TERCERO='CUANTIAS MENORES' THEN '169' ELSE C.CODPAIS END CODPAIS,
C.SALDOFINAL SALDOFINAL
FROM (
SELECT P.CONCEPTO,P.TIPO,P.NIT,P.DV,P.NOMBRES,P.DIRECCION,P.CODDPTO,P.CODCIUDAD,P.CODPAIS, SUM(P.SALDOFINAL) SALDOFINAL,
CHARINDEX(' ',P.NOMBRES) PRIMERESPACIO,
CHARINDEX(' ',P.NOMBRES,CHARINDEX(' ',P.NOMBRES)+1) SEGUNDOESPACIO,
CHARINDEX(' ',P.NOMBRES,CHARINDEX(' ',P.NOMBRES,CHARINDEX(' ',P.NOMBRES)+1)+1) TERCERESPACIO,
CHARINDEX(' ',P.NOMBRES,CHARINDEX(' ',P.NOMBRES,CHARINDEX(' ',P.NOMBRES,CHARINDEX(' ',P.NOMBRES)+1)+1)+1) CUARTOESPACIO,
 P.NOMBRES  TERCERO
FROM (
SELECT 
CASE WHEN (CV.cuenta LIKE '111005%' OR CV.cuenta LIKE '1125%') THEN 1110 ELSE 0  END CONCEPTO,
TR.tipo_identificacion TIPO,
TR.nit_real NIT, 
CAST(TR.digito AS VARCHAR(2)) DV,TR.nombres NOMBRES,ISNULL(TR.direccion,'') DIRECCION,TR.y_dpto CODDPTO,TR.y_ciudad CODCIUDAD,TR.y_pais CODPAIS,
CV.saldo_inicial + CV.debito - CV.credito SALDOFINAL
FROM cuentas_val CV INNER JOIN bancos B ON (CV.cuenta=B.cuenta)
 INNER JOIN terceros T ON (B.nit_banco=T.nit) INNER JOIN terceros TR ON (T.nit_real=TR.nit)
INNER JOIN y_ciudades YC ON (TR.y_ciudad=YC.ciudad AND TR.y_dpto=YC.departamento)
WHERE CV.ano=@AÑO AND CV.mes=@MES AND 
(CV.cuenta LIKE '111005%' OR CV.cuenta LIKE '1125%'))
AS P 
WHERE P.SALDOFINAL<>0
GROUP BY P.CONCEPTO,P.TIPO,P.NIT,P.DV,P.NOMBRES,P.DIRECCION,P.CODDPTO,P.CODCIUDAD,P.CODPAIS) AS C) AS Q

