DECLARE @AÑO AS INTEGER
DECLARE @MES AS INTEGER
DECLARE @CUANTIA AS MONEY
SET @AÑO=2014
SET @MES=12
SET @CUANTIA=0
SELECT Q.CONCEPTO,Q.TIPO,Q.NIT,'' DV,Q.PRIMERAPELLIDO,Q.SEGUNDOAPELLIDO,Q.PRIMERNOMBRE,Q.SEGUNDONOMBRE,Q.RAZONSOCIAL,Q.DIRECCION,Q.CODDPTO,Q.CODCIUDAD,Q.CODPAIS,
ROUND(SUM(Q.SALDOFINAL),0,0)*-1 SALDOFINAL
FROM (
SELECT C.CONCEPTO,
CASE WHEN C.TERCERO='CUANTIAS MENORES' THEN 43 ELSE
CASE WHEN C.TIPO='C' THEN 13 ELSE
CASE WHEN C.TIPO='N' THEN 31 ELSE
CASE WHEN C.TIPO='T' THEN 12 ELSE 0 END END END END TIPO,
CASE WHEN C.TERCERO='CUANTIAS MENORES' THEN 222222222 ELSE C.NIT END NIT,
CASE WHEN C.TERCERO='CUANTIAS MENORES' THEN ' ' ELSE 
CASE WHEN C.TIPO='N' THEN C.DV ELSE ' ' END END DV,
CASE WHEN C.TIPO IN ('C','T') AND C.TERCERO<>'CUANTIAS MENORES' THEN SUBSTRING(C.TERCERO,1,C.PRIMERESPACIO-1) ELSE '' END PRIMERAPELLIDO,
CASE WHEN (C.SEGUNDOESPACIO=0 OR C.TERCERESPACIO=0) AND C.TIPO IN ('C','T') AND C.TERCERO<>'CUANTIAS MENORES' THEN '' ELSE
CASE WHEN C.TIPO IN ('C','T') AND C.TERCERO<>'CUANTIAS MENORES' THEN SUBSTRING(C.TERCERO,C.PRIMERESPACIO+1,(C.SEGUNDOESPACIO-C.PRIMERESPACIO)-1) ELSE '' END END SEGUNDOAPELLIDO,
CASE WHEN (C.TERCERESPACIO=0) AND C.TIPO IN ('C','T') AND C.TERCERO<>'CUANTIAS MENORES' THEN SUBSTRING(C.TERCERO,C.PRIMERESPACIO+1,(C.SEGUNDOESPACIO-C.PRIMERESPACIO)-1) ELSE 
CASE WHEN (C.SEGUNDOESPACIO=0) AND C.TIPO IN ('C','T') AND C.TERCERO<>'CUANTIAS MENORES' THEN SUBSTRING(C.TERCERO,C.PRIMERESPACIO+1,LEN(C.TERCERO)) ELSE  
CASE WHEN C.TIPO IN ('C','T') AND C.TERCERO<>'CUANTIAS MENORES' THEN SUBSTRING(C.TERCERO,C.SEGUNDOESPACIO+1,(C.TERCERESPACIO-C.SEGUNDOESPACIO-1)) ELSE '' END END END PRIMERNOMBRE,
CASE WHEN (C.TERCERESPACIO=0 OR C.SEGUNDOESPACIO=0) AND C.TIPO IN ('C','T') AND C.TERCERO<>'CUANTIAS MENORES' THEN SUBSTRING(C.TERCERO,C.SEGUNDOESPACIO+1,LEN(C.TERCERO)) ELSE 
CASE WHEN C.TIPO IN ('C','T') AND C.TERCERO<>'CUANTIAS MENORES' THEN SUBSTRING(C.TERCERO,C.TERCERESPACIO+1,LEN(C.TERCERO)) ELSE '' END END SEGUNDONOMBRE,
CASE WHEN C.TIPO='N' OR C.TERCERO='CUANTIAS MENORES' THEN C.TERCERO ELSE '' END RAZONSOCIAL,
CASE WHEN C.TERCERO='CUANTIAS MENORES' THEN 'ENTRADA A GIRARDOTA ANTIGUA ESTACION FERROCARRIL' ELSE C.DIRECCION END DIRECCION,
CASE WHEN C.TERCERO='CUANTIAS MENORES' THEN '05' ELSE C.CODDPTO END CODDPTO,
CASE WHEN C.TERCERO='CUANTIAS MENORES' THEN '308' ELSE C.CODCIUDAD END CODCIUDAD,
CASE WHEN C.TERCERO='CUANTIAS MENORES' THEN '169' ELSE C.CODPAIS END CODPAIS,
C.SALDOFINAL SALDOFINAL
FROM (
SELECT P.CONCEPTO,P.TIPO,P.NIT,P.DV,P.NOMBRES,P.DIRECCION,P.CODDPTO,P.CODCIUDAD,P.CODPAIS, SUM(P.SALDOFINAL) SALDOFINAL,
CHARINDEX(' ',P.NOMBRES) PRIMERESPACIO,
CHARINDEX(' ',P.NOMBRES,CHARINDEX(' ',P.NOMBRES)+1) SEGUNDOESPACIO,
CHARINDEX(' ',P.NOMBRES,CHARINDEX(' ',P.NOMBRES,CHARINDEX(' ',P.NOMBRES)+1)+1) TERCERESPACIO,
CHARINDEX(' ',P.NOMBRES,CHARINDEX(' ',P.NOMBRES,CHARINDEX(' ',P.NOMBRES,CHARINDEX(' ',P.NOMBRES)+1)+1)+1) CUARTOESPACIO,
CASE WHEN SUM(P.SALDOFINAL)=0 THEN 'CUANTIAS MENORES' ELSE P.NOMBRES END TERCERO
FROM (
SELECT 
CASE WHEN CV.cuenta LIKE '22%' OR CV.cuenta LIKE '2335%' THEN 2201 
 WHEN CV.cuenta LIKE '21%' THEN 2203 
  WHEN CV.cuenta LIKE '2345%' THEN 2204 
 WHEN   CV.cuenta LIKE '2370%' OR CV.cuenta LIKE '2380%'  OR CV.cuenta LIKE '28%'  THEN 2206 
  WHEN CV.cuenta LIKE '25%' THEN 2205 
  ELSE 0 END CONCEPTO,
TR.tipo_identificacion TIPO,
TR.nit_real NIT, 
CAST(TR.digito AS VARCHAR(2)) DV,TR.nombres NOMBRES,ISNULL(TR.direccion,'') DIRECCION,TR.y_dpto CODDPTO,TR.y_ciudad CODCIUDAD,TR.y_pais CODPAIS,
CV.saldo_inicial + CV.debito - CV.credito SALDOFINAL
FROM cuentas_val CV INNER JOIN terceros T ON (CV.nit=T.nit) INNER JOIN terceros TR ON (T.nit_real=TR.nit)
INNER JOIN y_ciudades YC ON (TR.y_ciudad=YC.ciudad AND TR.y_dpto=YC.departamento)
WHERE CV.ano=2014 AND CV.mes=12 AND 
( CV.cuenta LIKE '22%' OR CV.cuenta LIKE '2335%' or CV.cuenta LIKE '21%' or CV.cuenta LIKE '2345%' or   CV.cuenta LIKE '2370%' OR CV.cuenta LIKE '2380%'  OR CV.cuenta LIKE '28%'  or  CV.cuenta LIKE '25%' ))
AS P 
WHERE P.SALDOFINAL<>0
GROUP BY P.CONCEPTO,P.TIPO,P.NIT,P.DV,P.NOMBRES,P.DIRECCION,P.CODDPTO,P.CODCIUDAD,P.CODPAIS) AS C) AS Q
GROUP BY  Q.CONCEPTO,Q.TIPO,Q.NIT,Q.DV,Q.PRIMERAPELLIDO,Q.SEGUNDOAPELLIDO,Q.PRIMERNOMBRE,Q.SEGUNDONOMBRE,Q.RAZONSOCIAL,Q.DIRECCION,Q.CODDPTO,Q.CODCIUDAD,Q.CODPAIS



