DECLARE @AÑO AS INTEGER
DECLARE @MES AS INTEGER
DECLARE @CUANTIA AS MONEY
SET @AÑO=2014
SET @MES=12
SET @CUANTIA=1000000
SELECT SAGRUPADA.CONCEPTO,SAGRUPADA.TIPO,SAGRUPADA.NIT,SAGRUPADA.DV,SAGRUPADA.PRIMERAPELLIDO,SAGRUPADA.SEGUNDOAPELLIDO,SAGRUPADA.PRIMERNOMBRE,SAGRUPADA.SEGUNDONOMBRE,SAGRUPADA.RAZONSOCIAL,SAGRUPADA.DIRECCION,SAGRUPADA.CODDPTO,SAGRUPADA.CODCIUDAD,SAGRUPADA.CODPAIS,
ROUND(SUM(SAGRUPADA.SALDOFINAL),0,0) SALDOFINAL
FROM (
SELECT 
SSEPARADA.CONCEPTO,
CASE WHEN SSEPARADA.TERCERO='CUANTIAS MENORES' THEN 43 ELSE
CASE WHEN SSEPARADA.TIPO='C' THEN 13 ELSE
CASE WHEN SSEPARADA.TIPO='N' THEN 31 ELSE
CASE WHEN SSEPARADA.TIPO='T' THEN 12 ELSE 0 END END END END TIPO,
CASE WHEN SSEPARADA.TERCERO='CUANTIAS MENORES' THEN 222222222 ELSE SSEPARADA.NIT END NIT,
' ' DV,
CASE WHEN SSEPARADA.TIPO IN ('C','T') AND SSEPARADA.TERCERO<>'CUANTIAS MENORES' THEN SUBSTRING(SSEPARADA.TERCERO,1,SSEPARADA.PRIMERESPACIO-1) ELSE '' END PRIMERAPELLIDO,
CASE WHEN (SSEPARADA.SEGUNDOESPACIO=0 OR SSEPARADA.TERCERESPACIO=0) AND SSEPARADA.TIPO IN ('C','T') AND SSEPARADA.TERCERO<>'CUANTIAS MENORES' THEN '' ELSE
CASE WHEN SSEPARADA.TIPO IN ('C','T') AND SSEPARADA.TERCERO<>'CUANTIAS MENORES' THEN SUBSTRING(SSEPARADA.TERCERO,SSEPARADA.PRIMERESPACIO+1,(SSEPARADA.SEGUNDOESPACIO-SSEPARADA.PRIMERESPACIO)-1) ELSE '' END END SEGUNDOAPELLIDO,
CASE WHEN (SSEPARADA.TERCERESPACIO=0) AND SSEPARADA.TIPO IN ('C','T') AND SSEPARADA.TERCERO<>'CUANTIAS MENORES' THEN SUBSTRING(SSEPARADA.TERCERO,SSEPARADA.PRIMERESPACIO+1,(SSEPARADA.SEGUNDOESPACIO-SSEPARADA.PRIMERESPACIO)-1) ELSE 
CASE WHEN (SSEPARADA.SEGUNDOESPACIO=0) AND SSEPARADA.TIPO IN ('C','T') AND SSEPARADA.TERCERO<>'CUANTIAS MENORES' THEN SUBSTRING(SSEPARADA.TERCERO,SSEPARADA.PRIMERESPACIO+1,LEN(SSEPARADA.TERCERO)) ELSE  
CASE WHEN SSEPARADA.TIPO IN ('C','T') AND SSEPARADA.TERCERO<>'CUANTIAS MENORES' THEN SUBSTRING(SSEPARADA.TERCERO,SSEPARADA.SEGUNDOESPACIO+1,(SSEPARADA.TERCERESPACIO-SSEPARADA.SEGUNDOESPACIO-1)) ELSE '' END END END PRIMERNOMBRE,
CASE WHEN (SSEPARADA.TERCERESPACIO=0 OR SSEPARADA.SEGUNDOESPACIO=0) AND SSEPARADA.TIPO IN ('C','T') AND SSEPARADA.TERCERO<>'CUANTIAS MENORES' THEN SUBSTRING(SSEPARADA.TERCERO,SSEPARADA.SEGUNDOESPACIO+1,LEN(SSEPARADA.TERCERO)) ELSE 
CASE WHEN SSEPARADA.TIPO IN ('C','T') AND SSEPARADA.TERCERO<>'CUANTIAS MENORES' THEN SUBSTRING(SSEPARADA.TERCERO,SSEPARADA.TERCERESPACIO+1,LEN(SSEPARADA.TERCERO)) ELSE '' END END SEGUNDONOMBRE,
CASE WHEN SSEPARADA.TIPO='N' OR SSEPARADA.TERCERO='CUANTIAS MENORES' THEN SSEPARADA.TERCERO ELSE '' END RAZONSOCIAL,
CASE WHEN SSEPARADA.TERCERO='CUANTIAS MENORES' THEN 'ENTRADA A GIRARDOTA ANTIGUA ESTACION FERROCARRIL' ELSE SSEPARADA.DIRECCION END DIRECCION,
CASE WHEN SSEPARADA.TERCERO='CUANTIAS MENORES' THEN '05' ELSE SSEPARADA.CODDPTO END CODDPTO,
CASE WHEN SSEPARADA.TERCERO='CUANTIAS MENORES' THEN '308' ELSE SSEPARADA.CODCIUDAD END CODCIUDAD,
CASE WHEN SSEPARADA.TERCERO='CUANTIAS MENORES' THEN '169' ELSE SSEPARADA.CODPAIS END CODPAIS,
SSEPARADA.SALDOFINAL SALDOFINAL
FROM (

SELECT *,
CHARINDEX(' ',PNORMAL.NOMBRES) PRIMERESPACIO,
CHARINDEX(' ',PNORMAL.NOMBRES,CHARINDEX(' ',PNORMAL.NOMBRES)+1) SEGUNDOESPACIO,
CHARINDEX(' ',PNORMAL.NOMBRES,CHARINDEX(' ',PNORMAL.NOMBRES,CHARINDEX(' ',PNORMAL.NOMBRES)+1)+1) TERCERESPACIO,
CHARINDEX(' ',PNORMAL.NOMBRES,CHARINDEX(' ',PNORMAL.NOMBRES,CHARINDEX(' ',PNORMAL.NOMBRES,CHARINDEX(' ',PNORMAL.NOMBRES)+1)+1)+1) CUARTOESPACIO,
CASE WHEN PNORMAL.NIT=9999 THEN 'CUANTIAS MENORES' ELSE PNORMAL.NOMBRES END TERCERO
FROM (

SELECT CN.CONCEPTO,CN.TIPO,CN.NIT,CN.DV,CN.NOMBRES,CN.DIRECCION,CN.CODDPTO,CN.CODCIUDAD,CN.CODPAIS,
CASE WHEN ROUND(SUM(CN.SALDOFINAL),0,0)<0 THEN  ROUND(SUM(CN.SALDOFINAL),0,0) ELSE ROUND(SUM(CN.SALDOFINAL),0,0) END SALDOFINAL
FROM (
SELECT 
CASE 
WHEN CV.cuenta LIKE '1305%' THEN 1315
WHEN CV.cuenta LIKE '1330%' OR CV.cuenta LIKE '1365%' OR CV.cuenta LIKE '1380%' THEN 1317
ELSE  0   END CONCEPTO,
TR.tipo_identificacion TIPO,
TR.nit_real NIT, 
' ' DV,TR.nombres NOMBRES,ISNULL(TR.direccion,'') DIRECCION,TR.y_dpto CODDPTO,TR.y_ciudad CODCIUDAD,TR.y_pais CODPAIS,
CV.saldo_inicial + CV.debito - CV.credito SALDOFINAL
FROM cuentas_val CV INNER JOIN terceros T ON (CV.nit=T.nit) INNER JOIN terceros TR ON (T.nit_real=TR.nit)
INNER JOIN y_ciudades YC ON (TR.y_ciudad=YC.ciudad AND TR.y_dpto=YC.departamento)
WHERE CV.ano=2014 AND CV.mes=12 AND 
(CV.cuenta LIKE '1305%' or CV.cuenta LIKE '1330%' OR CV.cuenta LIKE '1365%' OR CV.cuenta LIKE '1380%')

) AS CN
GROUP BY  CN.CONCEPTO,CN.TIPO,CN.NIT,CN.DV,CN.NOMBRES,CN.DIRECCION,CN.CODDPTO,CN.CODCIUDAD,CN.CODPAIS) AS PNORMAL

WHERE PNORMAL.SALDOFINAL<>0) AS SSEPARADA) AS SAGRUPADA
GROUP BY SAGRUPADA.CONCEPTO,SAGRUPADA.TIPO,SAGRUPADA.NIT,SAGRUPADA.
DV,SAGRUPADA.PRIMERAPELLIDO,SAGRUPADA.SEGUNDOAPELLIDO,SAGRUPADA.PRIMERNOMBRE,SAGRUPADA.SEGUNDONOMBRE,SAGRUPADA.RAZONSOCIAL,SAGRUPADA.DIRECCION,SAGRUPADA.CODDPTO,SAGRUPADA.CODCIUDAD,SAGRUPADA.CODPAIS