DECLARE @AÑO AS INTEGER
DECLARE @MES AS INTEGER
DECLARE @CUANTIA AS MONEY
SET @AÑO=2014
SET @MES=12
SET @CUANTIA=0
SELECT Q.TIPO,Q.NIT,Q.DV,Q.PRIMERAPELLIDO,Q.SEGUNDOAPELLIDO,Q.PRIMERNOMBRE,Q.SEGUNDONOMBRE,Q.RAZONSOCIAL,
CASE WHEN ROUND(SUM(Q.SALDOFINAL),0,0)<0 THEN ROUND(SUM(Q.SALDOFINAL),0,0)*-1 ELSE ROUND(SUM(Q.SALDOFINAL),0,0) END SALDOFINAL, SUM (Q.DEVOLUCION) DEVOLUCION
FROM (
SELECT 
CASE WHEN C.TERCERO='CUANTIAS MENORES' THEN 43 ELSE
CASE WHEN C.TIPO='C' THEN 13 ELSE
CASE WHEN C.TIPO='N' THEN 31 ELSE
CASE WHEN C.TIPO='T' THEN 12 ELSE 0 END END END END TIPO,
CASE WHEN C.TERCERO='CUANTIAS MENORES' THEN 222222222 ELSE C.NIT END NIT,
CASE WHEN C.TERCERO='CUANTIAS MENORES' THEN ' ' ELSE 
CASE WHEN C.TIPO='N' THEN C.DV ELSE ' ' END END DV,
CASE WHEN C.TIPO IN ('C','T') AND C.TERCERO<>'CUANTIAS MENORES' THEN SUBSTRING(C.TERCERO,1,C.PRIMERESPACIO-1) ELSE '' END PRIMERAPELLIDO,
CASE WHEN (C.SEGUNDOESPACIO=0 OR C.TERCERESPACIO=0) AND C.TIPO IN ('C','T') AND C.TERCERO<>'CUANTIAS MENORES' THEN '' ELSE
CASE WHEN C.TIPO IN ('C','T') AND C.TERCERO<>'CUANTIAS MENORES' THEN SUBSTRING(C.TERCERO,C.PRIMERESPACIO+1,(C.SEGUNDOESPACIO-C.PRIMERESPACIO)-1) ELSE '' END END SEGUNDOAPELLIDO,
CASE WHEN (C.TERCERESPACIO=0) AND C.TIPO IN ('C','T') AND C.TERCERO<>'CUANTIAS MENORES' THEN SUBSTRING(C.TERCERO,C.PRIMERESPACIO+1,(C.SEGUNDOESPACIO-C.PRIMERESPACIO)-1) ELSE 
CASE WHEN (C.SEGUNDOESPACIO=0) AND C.TIPO IN ('C','T') AND C.TERCERO<>'CUANTIAS MENORES' THEN SUBSTRING(C.TERCERO,C.PRIMERESPACIO+1,LEN(C.TERCERO)) ELSE  
CASE WHEN C.TIPO IN ('C','T') AND C.TERCERO<>'CUANTIAS MENORES' THEN SUBSTRING(C.TERCERO,C.SEGUNDOESPACIO+1,(C.TERCERESPACIO-C.SEGUNDOESPACIO-1)) ELSE '' END END END PRIMERNOMBRE,
CASE WHEN (C.TERCERESPACIO=0 OR C.SEGUNDOESPACIO=0) AND C.TIPO IN ('C','T') AND C.TERCERO<>'CUANTIAS MENORES' THEN SUBSTRING(C.TERCERO,C.SEGUNDOESPACIO+1,LEN(C.TERCERO)) ELSE 
CASE WHEN C.TIPO IN ('C','T') AND C.TERCERO<>'CUANTIAS MENORES' THEN SUBSTRING(C.TERCERO,C.TERCERESPACIO+1,LEN(C.TERCERO)) ELSE '' END END SEGUNDONOMBRE,
CASE WHEN C.TIPO='N' OR C.TERCERO='CUANTIAS MENORES' THEN C.TERCERO ELSE '' END RAZONSOCIAL,
C.SALDOFINAL SALDOFINAL,0 DEVOLUCION
FROM (
SELECT P.TIPO,P.NIT,P.DV,P.NOMBRES, SUM(P.SALDOFINAL) SALDOFINAL,
CHARINDEX(' ',P.NOMBRES) PRIMERESPACIO,
CHARINDEX(' ',P.NOMBRES,CHARINDEX(' ',P.NOMBRES)+1) SEGUNDOESPACIO,
CHARINDEX(' ',P.NOMBRES,CHARINDEX(' ',P.NOMBRES,CHARINDEX(' ',P.NOMBRES)+1)+1) TERCERESPACIO,
CHARINDEX(' ',P.NOMBRES,CHARINDEX(' ',P.NOMBRES,CHARINDEX(' ',P.NOMBRES,CHARINDEX(' ',P.NOMBRES)+1)+1)+1) CUARTOESPACIO,
 P.NOMBRES  TERCERO
FROM (
SELECT 
TR.tipo_identificacion TIPO,
TR.nit_real NIT, 
CAST(TR.digito AS VARCHAR(2)) DV,TR.nombres NOMBRES,
CV.saldo_inicial + CV.debito - CV.credito SALDOFINAL
FROM cuentas_val CV INNER JOIN terceros T ON (CV.nit=T.nit) INNER JOIN terceros TR ON (T.nit_real=TR.nit)
INNER JOIN y_ciudades YC ON (TR.y_ciudad=YC.ciudad AND TR.y_dpto=YC.departamento)
WHERE CV.ano=@AÑO AND CV.mes=@MES AND 
CV.cuenta IN ('24080501','24080503','24080504'))
AS P 
WHERE P.SALDOFINAL<>0
GROUP BY P.TIPO,P.NIT,P.DV,P.NOMBRES) AS C) AS Q
GROUP BY Q.TIPO,Q.NIT,Q.DV,Q.PRIMERAPELLIDO,Q.SEGUNDOAPELLIDO,Q.PRIMERNOMBRE,Q.SEGUNDONOMBRE,Q.RAZONSOCIAL
