DECLARE @AÑO AS INTEGER
DECLARE @MES AS INTEGER
DECLARE @CUANTIA AS MONEY
SET @AÑO=2014
SET @MES=12
SET @CUANTIA=-1000000
SELECT SAGRUPADA.CONCEPTO,SAGRUPADA.TIPO,SAGRUPADA.NIT,SAGRUPADA.DV,SAGRUPADA.PRIMERAPELLIDO,SAGRUPADA.SEGUNDOAPELLIDO,SAGRUPADA.PRIMERNOMBRE,SAGRUPADA.SEGUNDONOMBRE,SAGRUPADA.RAZONSOCIAL,SAGRUPADA.DIRECCION,SAGRUPADA.CODDPTO,SAGRUPADA.CODCIUDAD,SAGRUPADA.CODPAIS,
ROUND(SUM(SAGRUPADA.SALDOFINAL),0,0)*-1 SALDOFINAL
FROM (
SELECT 
SSEPARADA.CONCEPTO,
CASE WHEN SSEPARADA.TERCERO='CUANTIAS MENORES' THEN 43 ELSE
CASE WHEN SSEPARADA.TIPO='C' THEN 13 ELSE
CASE WHEN SSEPARADA.TIPO='N' THEN 31 ELSE
CASE WHEN SSEPARADA.TIPO='T' THEN 12 ELSE 0 END END END END TIPO,
CASE WHEN SSEPARADA.TERCERO='CUANTIAS MENORES' THEN 222222222 ELSE SSEPARADA.NIT END NIT,
' ' DV,
CASE WHEN SSEPARADA.TIPO IN ('C','T') AND SSEPARADA.TERCERO<>'CUANTIAS MENORES' THEN SUBSTRING(SSEPARADA.TERCERO,1,SSEPARADA.PRIMERESPACIO-1) ELSE '' END PRIMERAPELLIDO,
CASE WHEN (SSEPARADA.SEGUNDOESPACIO=0 OR SSEPARADA.TERCERESPACIO=0) AND SSEPARADA.TIPO IN ('C','T') AND SSEPARADA.TERCERO<>'CUANTIAS MENORES' THEN '' ELSE
CASE WHEN SSEPARADA.TIPO IN ('C','T') AND SSEPARADA.TERCERO<>'CUANTIAS MENORES' THEN SUBSTRING(SSEPARADA.TERCERO,SSEPARADA.PRIMERESPACIO+1,(SSEPARADA.SEGUNDOESPACIO-SSEPARADA.PRIMERESPACIO)-1) ELSE '' END END SEGUNDOAPELLIDO,
CASE WHEN (SSEPARADA.TERCERESPACIO=0) AND SSEPARADA.TIPO IN ('C','T') AND SSEPARADA.TERCERO<>'CUANTIAS MENORES' THEN SUBSTRING(SSEPARADA.TERCERO,SSEPARADA.PRIMERESPACIO+1,(SSEPARADA.SEGUNDOESPACIO-SSEPARADA.PRIMERESPACIO)-1) ELSE 
CASE WHEN (SSEPARADA.SEGUNDOESPACIO=0) AND SSEPARADA.TIPO IN ('C','T') AND SSEPARADA.TERCERO<>'CUANTIAS MENORES' THEN SUBSTRING(SSEPARADA.TERCERO,SSEPARADA.PRIMERESPACIO+1,LEN(SSEPARADA.TERCERO)) ELSE  
CASE WHEN SSEPARADA.TIPO IN ('C','T') AND SSEPARADA.TERCERO<>'CUANTIAS MENORES' THEN SUBSTRING(SSEPARADA.TERCERO,SSEPARADA.SEGUNDOESPACIO+1,(SSEPARADA.TERCERESPACIO-SSEPARADA.SEGUNDOESPACIO-1)) ELSE '' END END END PRIMERNOMBRE,
CASE WHEN (SSEPARADA.TERCERESPACIO=0 OR SSEPARADA.SEGUNDOESPACIO=0) AND SSEPARADA.TIPO IN ('C','T') AND SSEPARADA.TERCERO<>'CUANTIAS MENORES' THEN SUBSTRING(SSEPARADA.TERCERO,SSEPARADA.SEGUNDOESPACIO+1,LEN(SSEPARADA.TERCERO)) ELSE 
CASE WHEN SSEPARADA.TIPO IN ('C','T') AND SSEPARADA.TERCERO<>'CUANTIAS MENORES' THEN SUBSTRING(SSEPARADA.TERCERO,SSEPARADA.TERCERESPACIO+1,LEN(SSEPARADA.TERCERO)) ELSE '' END END SEGUNDONOMBRE,
CASE WHEN SSEPARADA.TIPO='N' OR SSEPARADA.TERCERO='CUANTIAS MENORES' THEN SSEPARADA.TERCERO ELSE '' END RAZONSOCIAL,
CASE WHEN SSEPARADA.TERCERO='CUANTIAS MENORES' THEN 'ENTRADA A GIRARDOTA ANTIGUA ESTACION FERROCARRIL' ELSE SSEPARADA.DIRECCION END DIRECCION,
CASE WHEN SSEPARADA.TERCERO='CUANTIAS MENORES' THEN '05' ELSE SSEPARADA.CODDPTO END CODDPTO,
CASE WHEN SSEPARADA.TERCERO='CUANTIAS MENORES' THEN '308' ELSE SSEPARADA.CODCIUDAD END CODCIUDAD,
CASE WHEN SSEPARADA.TERCERO='CUANTIAS MENORES' THEN '169' ELSE SSEPARADA.CODPAIS END CODPAIS,
SSEPARADA.SALDOFINAL SALDOFINAL
FROM (
SELECT *,
CHARINDEX(' ',PAGRUPADA.NOMBRES) PRIMERESPACIO,
CHARINDEX(' ',PAGRUPADA.NOMBRES,CHARINDEX(' ',PAGRUPADA.NOMBRES)+1) SEGUNDOESPACIO,
CHARINDEX(' ',PAGRUPADA.NOMBRES,CHARINDEX(' ',PAGRUPADA.NOMBRES,CHARINDEX(' ',PAGRUPADA.NOMBRES)+1)+1) TERCERESPACIO,
CHARINDEX(' ',PAGRUPADA.NOMBRES,CHARINDEX(' ',PAGRUPADA.NOMBRES,CHARINDEX(' ',PAGRUPADA.NOMBRES,CHARINDEX(' ',PAGRUPADA.NOMBRES)+1)+1)+1) CUARTOESPACIO,
CASE WHEN PAGRUPADA.SALDOFINAL>@CUANTIA OR PAGRUPADA.NIT=9999 THEN 'CUANTIAS MENORES' ELSE PAGRUPADA.NOMBRES END TERCERO
FROM (
SELECT PNORMAL.CONCEPTO,PNORMAL.TIPO,PNORMAL.NIT,PNORMAL.DV,PNORMAL.NOMBRES,PNORMAL.DIRECCION,PNORMAL.CODDPTO,PNORMAL.CODCIUDAD,PNORMAL.CODPAIS,
ROUND(SUM(PNORMAL.SALDOFINAL),0,0) SALDOFINAL
FROM (
SELECT 
CASE WHEN CV.cuenta IN ('130505','139001') THEN 1315 ELSE
CASE WHEN CV.cuenta IN ('131010','13250504','13250508','13250509','13250510') THEN 1316 ELSE
CASE WHEN CV.cuenta IN ('133005','133015','133095','13609504','136595','138095','13559501','135505') THEN 1317  ELSE  0   END END END CONCEPTO,
TR.tipo_identificacion TIPO,
TR.nit_real NIT, 
' ' DV,TR.nombres NOMBRES,ISNULL(TR.direccion,'') DIRECCION,TR.y_dpto CODDPTO,TR.y_ciudad CODCIUDAD,TR.y_pais CODPAIS,
CV.saldo_inicial + CV.debito - CV.credito SALDOFINAL
FROM cuentas_val CV INNER JOIN terceros T ON (CV.nit=T.nit) INNER JOIN terceros TR ON (T.nit_real=TR.nit)
INNER JOIN y_ciudades YC ON (TR.y_ciudad=YC.ciudad AND TR.y_dpto=YC.departamento)
WHERE CV.ano=@AÑO AND CV.mes=@MES AND 
CV.cuenta IN ('130505','139001','131010','13250504','13250508','13250509','13250510','133005','133015','133095','13609504','136595','138095','13559501','135505')
UNION
SELECT CN.CONCEPTO,T.tipo_identificacion TIPO,T.nit NIT, ' ' DV,
T.nombres NOMBRES,ISNULL(T.direccion,'') DIRECCION,T.y_dpto CODDPTO,T.y_ciudad CODCIUDAD,T.y_pais CODPAIS,
CASE WHEN CN.SALDOFINAL<0 THEN CN.SALDOFINAL*-1 ELSE CN.SALDOFINAL END SALDOFINAL
FROM (
SELECT 
CASE WHEN CV.cuenta IN ('13700501') THEN 1317 ELSE
CASE WHEN CV.cuenta IN ('139905') THEN 1318 ELSE  0    END END CONCEPTO,
CASE WHEN CV.cuenta IN ('13700501') THEN 800126239 ELSE
CASE WHEN CV.cuenta IN ('139905') THEN 811043174 ELSE  0    END END NIT,
CV.saldo_inicial + CV.debito - CV.credito SALDOFINAL
FROM cuentas_val CV 
WHERE CV.ano=@AÑO AND CV.mes=@MES AND 
CV.cuenta IN ('13700501','139905')) AS CN  INNER JOIN terceros T ON (CN.NIT=T.nit)) AS PNORMAL
GROUP BY PNORMAL.CONCEPTO,PNORMAL.TIPO,PNORMAL.NIT,PNORMAL.DV,PNORMAL.NOMBRES,PNORMAL.DIRECCION,PNORMAL.CODDPTO,PNORMAL.CODCIUDAD,PNORMAL.CODPAIS) AS PAGRUPADA
WHERE PAGRUPADA.SALDOFINAL<0) AS SSEPARADA) AS SAGRUPADA
GROUP BY SAGRUPADA.CONCEPTO,SAGRUPADA.TIPO,SAGRUPADA.NIT,SAGRUPADA.
DV,SAGRUPADA.PRIMERAPELLIDO,SAGRUPADA.SEGUNDOAPELLIDO,SAGRUPADA.PRIMERNOMBRE,SAGRUPADA.SEGUNDONOMBRE,SAGRUPADA.RAZONSOCIAL,SAGRUPADA.DIRECCION,SAGRUPADA.CODDPTO,SAGRUPADA.CODCIUDAD,SAGRUPADA.CODPAIS