DECLARE @AÑO AS INTEGER=2013
DECLARE @MES AS INTEGER=12
SELECT 
SSEPARADA.CONCEPTO,
CASE WHEN SSEPARADA.TERCERO='CUANTIAS MENORES' THEN 43 ELSE
CASE WHEN SSEPARADA.TIPO='C' THEN 13 ELSE
CASE WHEN SSEPARADA.TIPO='N' THEN 31 ELSE
CASE WHEN SSEPARADA.TIPO='T' THEN 12 ELSE 0 END END END END TIPO,
CASE WHEN SSEPARADA.TERCERO='CUANTIAS MENORES' THEN 222222222 ELSE SSEPARADA.NIT END NIT,
CASE WHEN TIPO='N' THEN DV ELSE '' END DV,
CASE WHEN SSEPARADA.TIPO IN ('C','T') AND SSEPARADA.TERCERO<>'CUANTIAS MENORES' THEN SUBSTRING(SSEPARADA.TERCERO,1,SSEPARADA.PRIMERESPACIO-1) ELSE '' END PRIMERAPELLIDO,
CASE WHEN (SSEPARADA.SEGUNDOESPACIO=0 OR SSEPARADA.TERCERESPACIO=0) AND SSEPARADA.TIPO IN ('C','T') AND SSEPARADA.TERCERO<>'CUANTIAS MENORES' THEN '' ELSE
CASE WHEN SSEPARADA.TIPO IN ('C','T') AND SSEPARADA.TERCERO<>'CUANTIAS MENORES' THEN SUBSTRING(SSEPARADA.TERCERO,SSEPARADA.PRIMERESPACIO+1,(SSEPARADA.SEGUNDOESPACIO-SSEPARADA.PRIMERESPACIO)-1) ELSE '' END END SEGUNDOAPELLIDO,
CASE WHEN (SSEPARADA.TERCERESPACIO=0) AND SSEPARADA.TIPO IN ('C','T') AND SSEPARADA.TERCERO<>'CUANTIAS MENORES' THEN SUBSTRING(SSEPARADA.TERCERO,SSEPARADA.PRIMERESPACIO+1,(SSEPARADA.SEGUNDOESPACIO-SSEPARADA.PRIMERESPACIO)-1) ELSE 
CASE WHEN (SSEPARADA.SEGUNDOESPACIO=0) AND SSEPARADA.TIPO IN ('C','T') AND SSEPARADA.TERCERO<>'CUANTIAS MENORES' THEN SUBSTRING(SSEPARADA.TERCERO,SSEPARADA.PRIMERESPACIO+1,LEN(SSEPARADA.TERCERO)) ELSE  
CASE WHEN SSEPARADA.TIPO IN ('C','T') AND SSEPARADA.TERCERO<>'CUANTIAS MENORES' THEN SUBSTRING(SSEPARADA.TERCERO,SSEPARADA.SEGUNDOESPACIO+1,(SSEPARADA.TERCERESPACIO-SSEPARADA.SEGUNDOESPACIO-1)) ELSE '' END END END PRIMERNOMBRE,
CASE WHEN (SSEPARADA.TERCERESPACIO=0 OR SSEPARADA.SEGUNDOESPACIO=0) AND SSEPARADA.TIPO IN ('C','T') AND SSEPARADA.TERCERO<>'CUANTIAS MENORES' THEN SUBSTRING(SSEPARADA.TERCERO,SSEPARADA.SEGUNDOESPACIO+1,LEN(SSEPARADA.TERCERO)) ELSE 
CASE WHEN SSEPARADA.TIPO IN ('C','T') AND SSEPARADA.TERCERO<>'CUANTIAS MENORES' THEN SUBSTRING(SSEPARADA.TERCERO,SSEPARADA.TERCERESPACIO+1,LEN(SSEPARADA.TERCERO)) ELSE '' END END SEGUNDONOMBRE,
CASE WHEN SSEPARADA.TIPO='N' OR SSEPARADA.TERCERO='CUANTIAS MENORES' THEN SSEPARADA.TERCERO ELSE '' END RAZONSOCIAL,
CASE WHEN SSEPARADA.TERCERO='CUANTIAS MENORES' THEN 'ENTRADA A GIRARDOTA ANTIGUA ESTACION FERROCARRIL' ELSE SSEPARADA.DIRECCION END DIRECCION,
CASE WHEN SSEPARADA.TERCERO='CUANTIAS MENORES' THEN '05' ELSE SSEPARADA.CODPTO END CODDPTO,
CASE WHEN SSEPARADA.TERCERO='CUANTIAS MENORES' THEN '308' ELSE SSEPARADA.CODMUN END CODCIUDAD,
CASE WHEN SSEPARADA.TERCERO='CUANTIAS MENORES' THEN '169' ELSE SSEPARADA.CODPAIS END CODPAIS,
SSEPARADA.SALDOFINAL SALDOFINAL
FROM (
SELECT *,
CHARINDEX(' ',PFINAL.NOMBRES) PRIMERESPACIO,
CHARINDEX(' ',PFINAL.NOMBRES,CHARINDEX(' ',PFINAL.NOMBRES)+1) SEGUNDOESPACIO,
CHARINDEX(' ',PFINAL.NOMBRES,CHARINDEX(' ',PFINAL.NOMBRES,CHARINDEX(' ',PFINAL.NOMBRES)+1)+1) TERCERESPACIO,
CHARINDEX(' ',PFINAL.NOMBRES,CHARINDEX(' ',PFINAL.NOMBRES,CHARINDEX(' ',PFINAL.NOMBRES,CHARINDEX(' ',PFINAL.NOMBRES)+1)+1)+1) CUARTOESPACIO,
PFINAL.NOMBRES TERCERO
FROM (
SELECT *
FROM (
SELECT PNORMAL.CONCEPTO,PNORMAL.TIPO,PNORMAL.NIT,PNORMAL.DV,PNORMAL.NOMBRES,PNORMAL.DIRECCION,PNORMAL.CODPTO,PNORMAL.CODMUN,PNORMAL.CODPAIS,ROUND(SUM(PNORMAL.SALDOFINAL),0,0) SALDOFINAL
FROM (
SELECT 
CASE WHEN ((CV.cuenta BETWEEN '5105' AND '51054504') OR (CV.cuenta BETWEEN '520503' AND '52054503')) OR (CV.cuenta IN ('52059503')) THEN 5001 ELSE  ---- OR(CV.cuenta IN ('26100502','26101002','26101502','26102002'))) dDEBITO
CASE WHEN  (CV.cuenta BETWEEN '5110' AND '511095') OR (CV.cuenta BETWEEN '52109501' AND '52109595')  THEN 5002 ELSE
CASE WHEN  (CV.cuenta BETWEEN '5235' AND '523595') OR (CV.cuenta BETWEEN '5135' AND '51359506')  OR (CV.cuenta BETWEEN '5145' AND '514595') OR (CV.cuenta BETWEEN '524515' AND '52454007')  THEN 5004 ELSE
CASE WHEN  (CV.cuenta BETWEEN '5120' AND '51209545') or (CV.cuenta BETWEEN '522010' AND '52209545')  THEN 5005 ELSE 
CASE WHEN  (CV.cuenta BETWEEN '530520' AND '530520')   THEN 5006 ELSE 
--CASE WHEN  (CV.cuenta BETWEEN '1435' AND '1436')  THEN 5007 ELSE   ---- COMPRAS DEBITOS
--CASE WHEN  (CV.cuenta BETWEEN '15' AND '16')  THEN 5008 ELSE ---- DEBITOS
CASE WHEN   (CV.cuenta BETWEEN '510572' AND '510578') or (CV.cuenta BETWEEN '520572' AND '520578')  THEN 5010 ELSE   
CASE WHEN   (CV.cuenta BETWEEN '510568' AND '510569') or (CV.cuenta BETWEEN '520568' AND '520569')   THEN 5011 ELSE 
CASE WHEN   (CV.cuenta IN ( '510570','510570')) THEN 5012 ELSE  
CASE WHEN  (CV.cuenta IN ('539525')) THEN 5013 ELSE 0 --- NO DEDUCIBLE
END END END END END END END END  END   CONCEPTO,
TR.tipo_identificacion TIPO,
TR.nit_real NIT, 
TR.digito DV,TR.nombres NOMBRES,TR.direccion DIRECCION,TR.y_dpto CODPTO,TR.y_ciudad CODMUN,TR.y_pais CODPAIS,
CV.debito-CV.credito SALDOFINAL
FROM cuentas_val CV INNER JOIN terceros T ON (CV.nit=T.nit) INNER JOIN terceros TR ON (T.nit_real=TR.nit)
WHERE CV.ano=@AÑO AND CV.mes<>13 AND 
(
(CV.cuenta BETWEEN '1435' AND '1436')  OR
(CV.cuenta BETWEEN '15' AND '16') 
)) AS PNORMAL
GROUP BY PNORMAL.CONCEPTO,PNORMAL.TIPO,PNORMAL.NIT,PNORMAL.DV,PNORMAL.NOMBRES,PNORMAL.DIRECCION,PNORMAL.CODPTO,PNORMAL.CODMUN,PNORMAL.CODPAIS) AS PAGRUPADA
WHERE PAGRUPADA.SALDOFINAL<>0
UNION
SELECT *
FROM (
SELECT PNORMAL.CONCEPTO,PNORMAL.TIPO,PNORMAL.NIT,PNORMAL.DV,PNORMAL.NOMBRES,PNORMAL.DIRECCION,PNORMAL.CODPTO,PNORMAL.CODMUN,PNORMAL.CODPAIS,ROUND(SUM(PNORMAL.SALDOFINAL),0,0) SALDOFINAL
FROM (
SELECT 
CASE WHEN  (CV.cuenta BETWEEN '5115' AND '511575') or (CV.cuenta BETWEEN '5215' AND '521575')  THEN 5015 ELSE --- CUENTA 511570,521570 COLUMNA IVA 
CASE WHEN (CV.cuenta IN ('52059502','510584')) OR  (CV.cuenta BETWEEN '510551' AND '510566') OR (CV.cuenta BETWEEN '510595' AND '51059509') OR 
(CV.cuenta BETWEEN '5125' AND '51309503') OR (CV.cuenta BETWEEN '514005' AND '514095') OR 
(CV.cuenta BETWEEN '515015' AND '51559505') OR (CV.cuenta BETWEEN '519510' AND '51959509') OR 
(CV.cuenta BETWEEN '519510' AND '51959509') OR (CV.cuenta BETWEEN '523040' AND '523075')  OR (CV.cuenta BETWEEN '524005' AND '524095') OR (CV.cuenta BETWEEN '52501504' AND '52959501')  
 OR (CV.cuenta BETWEEN '530505' AND '530515')   OR (CV.cuenta BETWEEN '530525' AND '531595')   OR (CV.cuenta BETWEEN '539520' AND '53959503') OR (CV.cuenta NOT IN (539525))  THEN 5016 ELSE  --- IVA NO DEDUCIBLE 531570
--CASE WHEN  (CV.cuenta BETWEEN '170595' AND '1710049502') THEN 5032 ELSE - MOVIMIENTO DEBITO
CASE WHEN (CV.cuenta IN ('17059502')) OR (CV.cuenta BETWEEN '1710' AND '171095')   THEN 5035 ELSE 
CASE WHEN (CV.cuenta IN ('519520'))  THEN 5056 ELSE 
CASE WHEN (CV.cuenta IN ('171095'))  THEN 5057 ELSE 
CASE WHEN (CV.cuenta IN ('512505'))  THEN 5058 ELSE 0   
END END END END END END  CONCEPTO,
TR.tipo_identificacion TIPO,
TR.nit_real NIT, 
' ' DV,TR.nombres NOMBRES,TR.direccion DIRECCION,TR.y_dpto CODPTO,TR.y_ciudad CODMUN,TR.y_pais CODPAIS,
CV.saldo_inicial+CV.debito-CV.credito SALDOFINAL
FROM cuentas_val CV INNER JOIN terceros T ON (CV.nit=T.nit) INNER JOIN terceros TR ON (T.nit_real=TR.nit)
WHERE CV.ano=@AÑO AND CV.mes=@MES AND 
(
(CV.cuenta IN ('17059502','519520','171095','512505')) OR
(CV.cuenta BETWEEN '5115' AND '511595') OR 
(CV.cuenta BETWEEN '5130' AND '51309503') OR
(CV.cuenta BETWEEN '5140' AND '51559502') OR
(CV.cuenta BETWEEN '51559504' AND '51559505') OR
(CV.cuenta BETWEEN '51952501' AND '51959509') OR
(CV.cuenta BETWEEN '525505' AND '52559502') OR
(CV.cuenta BETWEEN '52559504' AND '529535') OR
(CV.cuenta BETWEEN '170520' AND '17052070') OR
(CV.cuenta BETWEEN '1710' AND '171095')  
)) AS PNORMAL
GROUP BY PNORMAL.CONCEPTO,PNORMAL.TIPO,PNORMAL.NIT,PNORMAL.DV,PNORMAL.NOMBRES,PNORMAL.DIRECCION,PNORMAL.CODPTO,PNORMAL.CODMUN,PNORMAL.CODPAIS) AS PAGRUPADA
WHERE PAGRUPADA.SALDOFINAL<>0
UNION
SELECT *
FROM (
SELECT PNORMAL.CONCEPTO,PNORMAL.TIPO,PNORMAL.NIT,PNORMAL.DV,PNORMAL.NOMBRES,PNORMAL.DIRECCION,PNORMAL.CODPTO,PNORMAL.CODMUN,PNORMAL.CODPAIS,ROUND(SUM(PNORMAL.SALDOFINAL),0,0) SALDOFINAL
FROM (
SELECT 
CASE WHEN (CV.cuenta BETWEEN '1705' AND '171040')   THEN 5019 ELSE  0   
END CONCEPTO,
TR.tipo_identificacion TIPO,
TR.nit_real NIT, 
' ' DV,TR.nombres NOMBRES,TR.direccion DIRECCION,TR.y_dpto CODPTO,TR.y_ciudad CODMUN,TR.y_pais CODPAIS,
CV.credito SALDOFINAL
FROM cuentas_val CV INNER JOIN terceros T ON (T.nit=811043174) INNER JOIN terceros TR ON (T.nit_real=TR.nit)
WHERE CV.ano=@AÑO AND CV.mes<>@MES AND 
(
(CV.cuenta BETWEEN '1705' AND '171040') 
)) AS PNORMAL
GROUP BY PNORMAL.CONCEPTO,PNORMAL.TIPO,PNORMAL.NIT,PNORMAL.DV,PNORMAL.NOMBRES,PNORMAL.DIRECCION,PNORMAL.CODPTO,PNORMAL.CODMUN,PNORMAL.CODPAIS) AS PAGRUPADA
WHERE PAGRUPADA.SALDOFINAL<>0
UNION
SELECT *
FROM (
SELECT PNORMAL.CONCEPTO,PNORMAL.TIPO,PNORMAL.NIT,PNORMAL.DV,PNORMAL.NOMBRES,PNORMAL.DIRECCION,PNORMAL.CODPTO,PNORMAL.CODMUN,PNORMAL.CODPAIS,ROUND(SUM(PNORMAL.SALDOFINAL),0,0) SALDOFINAL
FROM (
SELECT 
CASE WHEN (CV.cuenta BETWEEN '1705' AND '171040')   THEN 5035 ELSE  0   
END CONCEPTO,
TR.tipo_identificacion TIPO,
TR.nit_real NIT, 
' ' DV,TR.nombres NOMBRES,TR.direccion DIRECCION,TR.y_dpto CODPTO,TR.y_ciudad CODMUN,TR.y_pais CODPAIS,
CV.debito SALDOFINAL
FROM cuentas_val CV INNER JOIN terceros T ON (CV.nit=T.nit) INNER JOIN terceros TR ON (T.nit_real=TR.nit)
WHERE CV.ano=@AÑO AND CV.mes<>@MES AND 
(
(CV.cuenta BETWEEN '1705' AND '171040') 
)) AS PNORMAL
GROUP BY PNORMAL.CONCEPTO,PNORMAL.TIPO,PNORMAL.NIT,PNORMAL.DV,PNORMAL.NOMBRES,PNORMAL.DIRECCION,PNORMAL.CODPTO,PNORMAL.CODMUN,PNORMAL.CODPAIS) AS PAGRUPADA
WHERE PAGRUPADA.SALDOFINAL<>0) AS PFINAL) AS SSEPARADA
WHERE SSEPARADA.CONCEPTO='5007'

